export type CompanySeed = {
  name: string;
  domain: string;
  industry: string;
  size: string;
};

export const companySeed: CompanySeed[] = [
  { name: "Google", domain: "google.com", industry: "Internet", size: "1000+" },
  { name: "Alphabet", domain: "abc.xyz", industry: "Internet", size: "1000+" },
  { name: "Amazon", domain: "amazon.com", industry: "E-commerce", size: "1000+" },
  { name: "Apple", domain: "apple.com", industry: "Consumer Tech", size: "1000+" },
  { name: "Microsoft", domain: "microsoft.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Meta", domain: "meta.com", industry: "Internet", size: "1000+" },
  { name: "Netflix", domain: "netflix.com", industry: "Media", size: "1000+" },
  { name: "Nvidia", domain: "nvidia.com", industry: "Semiconductors", size: "1000+" },
  { name: "Adobe", domain: "adobe.com", industry: "Software", size: "1000+" },
  { name: "Salesforce", domain: "salesforce.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Uber", domain: "uber.com", industry: "Mobility", size: "1000+" },
  { name: "Lyft", domain: "lyft.com", industry: "Mobility", size: "1000+" },
  { name: "Airbnb", domain: "airbnb.com", industry: "Travel", size: "1000+" },
  { name: "Stripe", domain: "stripe.com", industry: "Fintech", size: "1000+" },
  { name: "Square", domain: "squareup.com", industry: "Fintech", size: "1000+" },
  { name: "Block", domain: "block.xyz", industry: "Fintech", size: "1000+" },
  { name: "PayPal", domain: "paypal.com", industry: "Fintech", size: "1000+" },
  { name: "Intuit", domain: "intuit.com", industry: "Fintech", size: "1000+" },
  { name: "Shopify", domain: "shopify.com", industry: "E-commerce", size: "1000+" },
  { name: "Atlassian", domain: "atlassian.com", industry: "Software", size: "1000+" },
  { name: "ServiceNow", domain: "servicenow.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Workday", domain: "workday.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Snowflake", domain: "snowflake.com", industry: "Data", size: "1000+" },
  { name: "Databricks", domain: "databricks.com", industry: "Data", size: "1000+" },
  { name: "MongoDB", domain: "mongodb.com", industry: "Data", size: "1000+" },
  { name: "Elastic", domain: "elastic.co", industry: "Data", size: "1000+" },
  { name: "Palantir", domain: "palantir.com", industry: "Data", size: "1000+" },
  { name: "Twilio", domain: "twilio.com", industry: "Developer Tools", size: "1000+" },
  { name: "GitHub", domain: "github.com", industry: "Developer Tools", size: "1000+" },
  { name: "GitLab", domain: "gitlab.com", industry: "Developer Tools", size: "1000+" },
  { name: "Figma", domain: "figma.com", industry: "Design", size: "1000+" },
  { name: "Canva", domain: "canva.com", industry: "Design", size: "1000+" },
  { name: "Notion", domain: "notion.so", industry: "Productivity", size: "1000+" },
  { name: "Slack", domain: "slack.com", industry: "Productivity", size: "1000+" },
  { name: "Zoom", domain: "zoom.us", industry: "Productivity", size: "1000+" },
  { name: "Asana", domain: "asana.com", industry: "Productivity", size: "1000+" },
  { name: "Miro", domain: "miro.com", industry: "Productivity", size: "1000+" },
  { name: "Monday.com", domain: "monday.com", industry: "Productivity", size: "1000+" },
  { name: "Dropbox", domain: "dropbox.com", industry: "Cloud Storage", size: "1000+" },
  { name: "Box", domain: "box.com", industry: "Cloud Storage", size: "1000+" },
  { name: "Salesloft", domain: "salesloft.com", industry: "SaaS", size: "501-1000" },
  { name: "HubSpot", domain: "hubspot.com", industry: "SaaS", size: "1000+" },
  { name: "Zendesk", domain: "zendesk.com", industry: "SaaS", size: "1000+" },
  { name: "Intercom", domain: "intercom.com", industry: "SaaS", size: "1000+" },
  { name: "Okta", domain: "okta.com", industry: "Security", size: "1000+" },
  { name: "Auth0", domain: "auth0.com", industry: "Security", size: "1000+" },
  { name: "CrowdStrike", domain: "crowdstrike.com", industry: "Security", size: "1000+" },
  { name: "Palo Alto Networks", domain: "paloaltonetworks.com", industry: "Security", size: "1000+" },
  { name: "Zscaler", domain: "zscaler.com", industry: "Security", size: "1000+" },
  { name: "Cloudflare", domain: "cloudflare.com", industry: "Security", size: "1000+" },
  { name: "Akamai", domain: "akamai.com", industry: "Infrastructure", size: "1000+" },
  { name: "DigitalOcean", domain: "digitalocean.com", industry: "Cloud", size: "1000+" },
  { name: "Heroku", domain: "heroku.com", industry: "Cloud", size: "1000+" },
  { name: "HashiCorp", domain: "hashicorp.com", industry: "Infrastructure", size: "1000+" },
  { name: "Fastly", domain: "fastly.com", industry: "Infrastructure", size: "1000+" },
  { name: "Datadog", domain: "datadoghq.com", industry: "Infrastructure", size: "1000+" },
  { name: "New Relic", domain: "newrelic.com", industry: "Infrastructure", size: "1000+" },
  { name: "Snyk", domain: "snyk.io", industry: "Security", size: "1000+" },
  { name: "PagerDuty", domain: "pagerduty.com", industry: "Infrastructure", size: "1000+" },
  { name: "Sumo Logic", domain: "sumologic.com", industry: "Infrastructure", size: "1000+" },
  { name: "Splunk", domain: "splunk.com", industry: "Data", size: "1000+" },
  { name: "Confluent", domain: "confluent.io", industry: "Data", size: "1000+" },
  { name: "DataStax", domain: "datastax.com", industry: "Data", size: "501-1000" },
  { name: "Couchbase", domain: "couchbase.com", industry: "Data", size: "1000+" },
  { name: "Redis", domain: "redis.io", industry: "Data", size: "501-1000" },
  { name: "Cockroach Labs", domain: "cockroachlabs.com", industry: "Data", size: "501-1000" },
  { name: "SingleStore", domain: "singlestore.com", industry: "Data", size: "501-1000" },
  { name: "PlanetScale", domain: "planetscale.com", industry: "Data", size: "201-500" },
  { name: "Vercel", domain: "vercel.com", industry: "Developer Tools", size: "501-1000" },
  { name: "Netlify", domain: "netlify.com", industry: "Developer Tools", size: "501-1000" },
  { name: "Render", domain: "render.com", industry: "Cloud", size: "201-500" },
  { name: "Supabase", domain: "supabase.com", industry: "Developer Tools", size: "201-500" },
  { name: "Linear", domain: "linear.app", industry: "Productivity", size: "201-500" },
  { name: "Airtable", domain: "airtable.com", industry: "Productivity", size: "1000+" },
  { name: "Coda", domain: "coda.io", industry: "Productivity", size: "201-500" },
  { name: "ClickUp", domain: "clickup.com", industry: "Productivity", size: "1000+" },
  { name: "Smartsheet", domain: "smartsheet.com", industry: "Productivity", size: "1000+" },
  { name: "Zapier", domain: "zapier.com", industry: "Automation", size: "1000+" },
  { name: "IFTTT", domain: "ifttt.com", industry: "Automation", size: "51-200" },
  { name: "Braze", domain: "braze.com", industry: "Marketing", size: "1000+" },
  { name: "Segment", domain: "segment.com", industry: "Marketing", size: "1000+" },
  { name: "Amplitude", domain: "amplitude.com", industry: "Analytics", size: "1000+" },
  { name: "Mixpanel", domain: "mixpanel.com", industry: "Analytics", size: "501-1000" },
  { name: "Heap", domain: "heap.io", industry: "Analytics", size: "201-500" },
  { name: "Looker", domain: "looker.com", industry: "Analytics", size: "1000+" },
  { name: "Tableau", domain: "tableau.com", industry: "Analytics", size: "1000+" },
  { name: "Mode", domain: "mode.com", industry: "Analytics", size: "201-500" },
  { name: "Fivetran", domain: "fivetran.com", industry: "Data", size: "1000+" },
  { name: "dbt Labs", domain: "getdbt.com", industry: "Data", size: "1000+" },
  { name: "Prefect", domain: "prefect.io", industry: "Data", size: "201-500" },
  { name: "Astronomer", domain: "astronomer.io", industry: "Data", size: "201-500" },
  { name: "Snowplow", domain: "snowplow.io", industry: "Data", size: "201-500" },
  { name: "Starburst", domain: "starburst.io", industry: "Data", size: "501-1000" },
  { name: "MuleSoft", domain: "mulesoft.com", industry: "Integration", size: "1000+" },
  { name: "Workato", domain: "workato.com", industry: "Automation", size: "1000+" },
  { name: "UiPath", domain: "uipath.com", industry: "Automation", size: "1000+" },
  { name: "Automation Anywhere", domain: "automationanywhere.com", industry: "Automation", size: "1000+" },
  { name: "Oracle", domain: "oracle.com", industry: "Enterprise Software", size: "1000+" },
  { name: "SAP", domain: "sap.com", industry: "Enterprise Software", size: "1000+" },
  { name: "IBM", domain: "ibm.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Cisco", domain: "cisco.com", industry: "Networking", size: "1000+" },
  { name: "VMware", domain: "vmware.com", industry: "Infrastructure", size: "1000+" },
  { name: "Dell", domain: "dell.com", industry: "Hardware", size: "1000+" },
  { name: "HP", domain: "hp.com", industry: "Hardware", size: "1000+" },
  { name: "Lenovo", domain: "lenovo.com", industry: "Hardware", size: "1000+" },
  { name: "Intel", domain: "intel.com", industry: "Semiconductors", size: "1000+" },
  { name: "AMD", domain: "amd.com", industry: "Semiconductors", size: "1000+" },
  { name: "Qualcomm", domain: "qualcomm.com", industry: "Semiconductors", size: "1000+" },
  { name: "Broadcom", domain: "broadcom.com", industry: "Semiconductors", size: "1000+" },
  { name: "ARM", domain: "arm.com", industry: "Semiconductors", size: "1000+" },
  { name: "ServiceTitan", domain: "servicetitan.com", industry: "SaaS", size: "1000+" },
  { name: "Toast", domain: "toasttab.com", industry: "Fintech", size: "1000+" },
  { name: "DoorDash", domain: "doordash.com", industry: "Logistics", size: "1000+" },
  { name: "Instacart", domain: "instacart.com", industry: "Logistics", size: "1000+" },
  { name: "Gusto", domain: "gusto.com", industry: "Fintech", size: "1000+" },
  { name: "Rippling", domain: "rippling.com", industry: "HR Tech", size: "1000+" },
  { name: "Carta", domain: "carta.com", industry: "Fintech", size: "1000+" },
  { name: "Brex", domain: "brex.com", industry: "Fintech", size: "1000+" },
  { name: "Ramp", domain: "ramp.com", industry: "Fintech", size: "1000+" },
  { name: "Chime", domain: "chime.com", industry: "Fintech", size: "1000+" },
  { name: "Robinhood", domain: "robinhood.com", industry: "Fintech", size: "1000+" },
  { name: "Coinbase", domain: "coinbase.com", industry: "Fintech", size: "1000+" },
  { name: "Plaid", domain: "plaid.com", industry: "Fintech", size: "1000+" },
  { name: "Affirm", domain: "affirm.com", industry: "Fintech", size: "1000+" },
  { name: "SoFi", domain: "sofi.com", industry: "Fintech", size: "1000+" },
  { name: "Klarna", domain: "klarna.com", industry: "Fintech", size: "1000+" },
  { name: "Wise", domain: "wise.com", industry: "Fintech", size: "1000+" },
  { name: "Xero", domain: "xero.com", industry: "Fintech", size: "1000+" },
  { name: "FreshBooks", domain: "freshbooks.com", industry: "Fintech", size: "201-500" },
  { name: "Bill.com", domain: "bill.com", industry: "Fintech", size: "1000+" },
  { name: "Anthropic", domain: "anthropic.com", industry: "AI", size: "201-500" },
  { name: "OpenAI", domain: "openai.com", industry: "AI", size: "1000+" },
  { name: "Hugging Face", domain: "huggingface.co", industry: "AI", size: "501-1000" },
  { name: "Cohere", domain: "cohere.com", industry: "AI", size: "201-500" },
  { name: "Scale AI", domain: "scale.com", industry: "AI", size: "1000+" },
  { name: "Mistral", domain: "mistral.ai", industry: "AI", size: "201-500" },
  { name: "DeepMind", domain: "deepmind.com", industry: "AI", size: "1000+" },
  { name: "Waymo", domain: "waymo.com", industry: "Autonomous", size: "1000+" },
  { name: "Cruise", domain: "getcruise.com", industry: "Autonomous", size: "1000+" },
  { name: "Tesla", domain: "tesla.com", industry: "Automotive", size: "1000+" },
  { name: "Rivian", domain: "rivian.com", industry: "Automotive", size: "1000+" },
  { name: "Lucid", domain: "lucidmotors.com", industry: "Automotive", size: "1000+" },
  { name: "Anduril", domain: "anduril.com", industry: "Defense", size: "1000+" },
  { name: "Booz Allen", domain: "boozallen.com", industry: "Consulting", size: "1000+" },
  { name: "Accenture", domain: "accenture.com", industry: "Consulting", size: "1000+" },
  { name: "McKinsey", domain: "mckinsey.com", industry: "Consulting", size: "1000+" },
  { name: "BCG", domain: "bcg.com", industry: "Consulting", size: "1000+" },
  { name: "Deloitte", domain: "deloitte.com", industry: "Consulting", size: "1000+" },
  { name: "KPMG", domain: "kpmg.com", industry: "Consulting", size: "1000+" },
  { name: "PwC", domain: "pwc.com", industry: "Consulting", size: "1000+" },
  { name: "EY", domain: "ey.com", industry: "Consulting", size: "1000+" },
  { name: "Etsy", domain: "etsy.com", industry: "E-commerce", size: "1000+" },
  { name: "eBay", domain: "ebay.com", industry: "E-commerce", size: "1000+" },
  { name: "Walmart Global Tech", domain: "walmart.com", industry: "Retail", size: "1000+" },
  { name: "Target", domain: "target.com", industry: "Retail", size: "1000+" },
  { name: "Costco", domain: "costco.com", industry: "Retail", size: "1000+" },
  { name: "Deliveroo", domain: "deliveroo.com", industry: "Logistics", size: "1000+" },
  { name: "Grubhub", domain: "grubhub.com", industry: "Logistics", size: "1000+" },
  { name: "Flexport", domain: "flexport.com", industry: "Logistics", size: "1000+" },
  { name: "Shippo", domain: "goshippo.com", industry: "Logistics", size: "201-500" },
  { name: "ShipBob", domain: "shipbob.com", industry: "Logistics", size: "1000+" },
  { name: "Postman", domain: "postman.com", industry: "Developer Tools", size: "1000+" },
  { name: "Sentry", domain: "sentry.io", industry: "Developer Tools", size: "1000+" },
  { name: "CircleCI", domain: "circleci.com", industry: "Developer Tools", size: "1000+" },
  { name: "Travis CI", domain: "travis-ci.com", industry: "Developer Tools", size: "201-500" },
  { name: "Circle", domain: "circle.com", industry: "Fintech", size: "1000+" },
  { name: "Binance", domain: "binance.com", industry: "Fintech", size: "1000+" },
  { name: "Kraken", domain: "kraken.com", industry: "Fintech", size: "1000+" },
  { name: "Duolingo", domain: "duolingo.com", industry: "Consumer", size: "1000+" },
  { name: "Khan Academy", domain: "khanacademy.org", industry: "Education", size: "201-500" },
  { name: "Coursera", domain: "coursera.org", industry: "Education", size: "1000+" },
  { name: "Udemy", domain: "udemy.com", industry: "Education", size: "1000+" },
  { name: "Udacity", domain: "udacity.com", industry: "Education", size: "201-500" },
  { name: "Skillshare", domain: "skillshare.com", industry: "Education", size: "201-500" },
  { name: "Quizlet", domain: "quizlet.com", industry: "Education", size: "201-500" },
  { name: "Chegg", domain: "chegg.com", industry: "Education", size: "1000+" },
  { name: "Robinhood Markets", domain: "robinhood.com", industry: "Fintech", size: "1000+" },
  { name: "Airbyte", domain: "airbyte.com", industry: "Data", size: "501-1000" },
  { name: "RudderStack", domain: "rudderstack.com", industry: "Data", size: "201-500" },
  { name: "Abnormal Security", domain: "abnormalsecurity.com", industry: "Security", size: "1000+" },
  { name: "SentinelOne", domain: "sentinelone.com", industry: "Security", size: "1000+" },
  { name: "Rapid7", domain: "rapid7.com", industry: "Security", size: "1000+" },
  { name: "DuckDuckGo", domain: "duckduckgo.com", industry: "Consumer", size: "201-500" },
  { name: "Mozilla", domain: "mozilla.org", industry: "Consumer", size: "1000+" },
  { name: "Pinterest", domain: "pinterest.com", industry: "Consumer", size: "1000+" },
  { name: "Snap", domain: "snap.com", industry: "Consumer", size: "1000+" },
  { name: "TikTok", domain: "tiktok.com", industry: "Consumer", size: "1000+" },
  { name: "ByteDance", domain: "bytedance.com", industry: "Consumer", size: "1000+" },
  { name: "Reddit", domain: "reddit.com", industry: "Consumer", size: "1000+" },
  { name: "Spotify", domain: "spotify.com", industry: "Media", size: "1000+" },
  { name: "SoundCloud", domain: "soundcloud.com", industry: "Media", size: "201-500" },
  { name: "Twitch", domain: "twitch.tv", industry: "Media", size: "1000+" },
  { name: "Roblox", domain: "roblox.com", industry: "Gaming", size: "1000+" },
  { name: "Epic Games", domain: "epicgames.com", industry: "Gaming", size: "1000+" },
  { name: "Unity", domain: "unity.com", industry: "Gaming", size: "1000+" },
  { name: "Niantic", domain: "nianticlabs.com", industry: "Gaming", size: "501-1000" },
  { name: "Electronic Arts", domain: "ea.com", industry: "Gaming", size: "1000+" },
  { name: "Activision Blizzard", domain: "activisionblizzard.com", industry: "Gaming", size: "1000+" },
  { name: "Zynga", domain: "zynga.com", industry: "Gaming", size: "1000+" },
  { name: "Riot Games", domain: "riotgames.com", industry: "Gaming", size: "1000+" },
];
