export type CompanySeed = {
  name: string;
  domain: string;
  industry: string;
  size: string;
};

const baseCompanySeed: CompanySeed[] = [
  { name: "Google", domain: "google.com", industry: "Internet", size: "1000+" },
  { name: "Alphabet", domain: "abc.xyz", industry: "Internet", size: "1000+" },
  { name: "Amazon", domain: "amazon.com", industry: "E-commerce", size: "1000+" },
  { name: "Apple", domain: "apple.com", industry: "Consumer Tech", size: "1000+" },
  { name: "Microsoft", domain: "microsoft.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Meta", domain: "meta.com", industry: "Internet", size: "1000+" },
  { name: "Netflix", domain: "netflix.com", industry: "Media", size: "1000+" },
  { name: "Nvidia", domain: "nvidia.com", industry: "Semiconductors", size: "1000+" },
  { name: "Adobe", domain: "adobe.com", industry: "Software", size: "1000+" },
  { name: "Salesforce", domain: "salesforce.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Uber", domain: "uber.com", industry: "Mobility", size: "1000+" },
  { name: "Lyft", domain: "lyft.com", industry: "Mobility", size: "1000+" },
  { name: "Airbnb", domain: "airbnb.com", industry: "Travel", size: "1000+" },
  { name: "Stripe", domain: "stripe.com", industry: "Fintech", size: "1000+" },
  { name: "Square", domain: "squareup.com", industry: "Fintech", size: "1000+" },
  { name: "Block", domain: "block.xyz", industry: "Fintech", size: "1000+" },
  { name: "PayPal", domain: "paypal.com", industry: "Fintech", size: "1000+" },
  { name: "Intuit", domain: "intuit.com", industry: "Fintech", size: "1000+" },
  { name: "Shopify", domain: "shopify.com", industry: "E-commerce", size: "1000+" },
  { name: "Atlassian", domain: "atlassian.com", industry: "Software", size: "1000+" },
  { name: "ServiceNow", domain: "servicenow.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Workday", domain: "workday.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Snowflake", domain: "snowflake.com", industry: "Data", size: "1000+" },
  { name: "Databricks", domain: "databricks.com", industry: "Data", size: "1000+" },
  { name: "MongoDB", domain: "mongodb.com", industry: "Data", size: "1000+" },
  { name: "Elastic", domain: "elastic.co", industry: "Data", size: "1000+" },
  { name: "Palantir", domain: "palantir.com", industry: "Data", size: "1000+" },
  { name: "Twilio", domain: "twilio.com", industry: "Developer Tools", size: "1000+" },
  { name: "GitHub", domain: "github.com", industry: "Developer Tools", size: "1000+" },
  { name: "GitLab", domain: "gitlab.com", industry: "Developer Tools", size: "1000+" },
  { name: "Figma", domain: "figma.com", industry: "Design", size: "1000+" },
  { name: "Canva", domain: "canva.com", industry: "Design", size: "1000+" },
  { name: "Notion", domain: "notion.so", industry: "Productivity", size: "1000+" },
  { name: "Slack", domain: "slack.com", industry: "Productivity", size: "1000+" },
  { name: "Zoom", domain: "zoom.us", industry: "Productivity", size: "1000+" },
  { name: "Asana", domain: "asana.com", industry: "Productivity", size: "1000+" },
  { name: "Miro", domain: "miro.com", industry: "Productivity", size: "1000+" },
  { name: "Monday.com", domain: "monday.com", industry: "Productivity", size: "1000+" },
  { name: "Dropbox", domain: "dropbox.com", industry: "Cloud Storage", size: "1000+" },
  { name: "Box", domain: "box.com", industry: "Cloud Storage", size: "1000+" },
  { name: "Salesloft", domain: "salesloft.com", industry: "SaaS", size: "501-1000" },
  { name: "HubSpot", domain: "hubspot.com", industry: "SaaS", size: "1000+" },
  { name: "Zendesk", domain: "zendesk.com", industry: "SaaS", size: "1000+" },
  { name: "Intercom", domain: "intercom.com", industry: "SaaS", size: "1000+" },
  { name: "Okta", domain: "okta.com", industry: "Security", size: "1000+" },
  { name: "Auth0", domain: "auth0.com", industry: "Security", size: "1000+" },
  { name: "CrowdStrike", domain: "crowdstrike.com", industry: "Security", size: "1000+" },
  { name: "Palo Alto Networks", domain: "paloaltonetworks.com", industry: "Security", size: "1000+" },
  { name: "Zscaler", domain: "zscaler.com", industry: "Security", size: "1000+" },
  { name: "Cloudflare", domain: "cloudflare.com", industry: "Security", size: "1000+" },
  { name: "Akamai", domain: "akamai.com", industry: "Infrastructure", size: "1000+" },
  { name: "DigitalOcean", domain: "digitalocean.com", industry: "Cloud", size: "1000+" },
  { name: "Heroku", domain: "heroku.com", industry: "Cloud", size: "1000+" },
  { name: "HashiCorp", domain: "hashicorp.com", industry: "Infrastructure", size: "1000+" },
  { name: "Fastly", domain: "fastly.com", industry: "Infrastructure", size: "1000+" },
  { name: "Datadog", domain: "datadoghq.com", industry: "Infrastructure", size: "1000+" },
  { name: "New Relic", domain: "newrelic.com", industry: "Infrastructure", size: "1000+" },
  { name: "Snyk", domain: "snyk.io", industry: "Security", size: "1000+" },
  { name: "PagerDuty", domain: "pagerduty.com", industry: "Infrastructure", size: "1000+" },
  { name: "Sumo Logic", domain: "sumologic.com", industry: "Infrastructure", size: "1000+" },
  { name: "Splunk", domain: "splunk.com", industry: "Data", size: "1000+" },
  { name: "Confluent", domain: "confluent.io", industry: "Data", size: "1000+" },
  { name: "DataStax", domain: "datastax.com", industry: "Data", size: "501-1000" },
  { name: "Couchbase", domain: "couchbase.com", industry: "Data", size: "1000+" },
  { name: "Redis", domain: "redis.io", industry: "Data", size: "501-1000" },
  { name: "Cockroach Labs", domain: "cockroachlabs.com", industry: "Data", size: "501-1000" },
  { name: "SingleStore", domain: "singlestore.com", industry: "Data", size: "501-1000" },
  { name: "PlanetScale", domain: "planetscale.com", industry: "Data", size: "201-500" },
  { name: "Vercel", domain: "vercel.com", industry: "Developer Tools", size: "501-1000" },
  { name: "Netlify", domain: "netlify.com", industry: "Developer Tools", size: "501-1000" },
  { name: "Render", domain: "render.com", industry: "Cloud", size: "201-500" },
  { name: "Supabase", domain: "supabase.com", industry: "Developer Tools", size: "201-500" },
  { name: "Linear", domain: "linear.app", industry: "Productivity", size: "201-500" },
  { name: "Airtable", domain: "airtable.com", industry: "Productivity", size: "1000+" },
  { name: "Coda", domain: "coda.io", industry: "Productivity", size: "201-500" },
  { name: "ClickUp", domain: "clickup.com", industry: "Productivity", size: "1000+" },
  { name: "Smartsheet", domain: "smartsheet.com", industry: "Productivity", size: "1000+" },
  { name: "Zapier", domain: "zapier.com", industry: "Automation", size: "1000+" },
  { name: "IFTTT", domain: "ifttt.com", industry: "Automation", size: "51-200" },
  { name: "Braze", domain: "braze.com", industry: "Marketing", size: "1000+" },
  { name: "Segment", domain: "segment.com", industry: "Marketing", size: "1000+" },
  { name: "Amplitude", domain: "amplitude.com", industry: "Analytics", size: "1000+" },
  { name: "Mixpanel", domain: "mixpanel.com", industry: "Analytics", size: "501-1000" },
  { name: "Heap", domain: "heap.io", industry: "Analytics", size: "201-500" },
  { name: "Looker", domain: "looker.com", industry: "Analytics", size: "1000+" },
  { name: "Tableau", domain: "tableau.com", industry: "Analytics", size: "1000+" },
  { name: "Mode", domain: "mode.com", industry: "Analytics", size: "201-500" },
  { name: "Fivetran", domain: "fivetran.com", industry: "Data", size: "1000+" },
  { name: "dbt Labs", domain: "getdbt.com", industry: "Data", size: "1000+" },
  { name: "Prefect", domain: "prefect.io", industry: "Data", size: "201-500" },
  { name: "Astronomer", domain: "astronomer.io", industry: "Data", size: "201-500" },
  { name: "Snowplow", domain: "snowplow.io", industry: "Data", size: "201-500" },
  { name: "Starburst", domain: "starburst.io", industry: "Data", size: "501-1000" },
  { name: "MuleSoft", domain: "mulesoft.com", industry: "Integration", size: "1000+" },
  { name: "Workato", domain: "workato.com", industry: "Automation", size: "1000+" },
  { name: "UiPath", domain: "uipath.com", industry: "Automation", size: "1000+" },
  { name: "Automation Anywhere", domain: "automationanywhere.com", industry: "Automation", size: "1000+" },
  { name: "Oracle", domain: "oracle.com", industry: "Enterprise Software", size: "1000+" },
  { name: "SAP", domain: "sap.com", industry: "Enterprise Software", size: "1000+" },
  { name: "IBM", domain: "ibm.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Cisco", domain: "cisco.com", industry: "Networking", size: "1000+" },
  { name: "VMware", domain: "vmware.com", industry: "Infrastructure", size: "1000+" },
  { name: "Dell", domain: "dell.com", industry: "Hardware", size: "1000+" },
  { name: "HP", domain: "hp.com", industry: "Hardware", size: "1000+" },
  { name: "Lenovo", domain: "lenovo.com", industry: "Hardware", size: "1000+" },
  { name: "Intel", domain: "intel.com", industry: "Semiconductors", size: "1000+" },
  { name: "AMD", domain: "amd.com", industry: "Semiconductors", size: "1000+" },
  { name: "Qualcomm", domain: "qualcomm.com", industry: "Semiconductors", size: "1000+" },
  { name: "Broadcom", domain: "broadcom.com", industry: "Semiconductors", size: "1000+" },
  { name: "ARM", domain: "arm.com", industry: "Semiconductors", size: "1000+" },
  { name: "ServiceTitan", domain: "servicetitan.com", industry: "SaaS", size: "1000+" },
  { name: "Toast", domain: "toasttab.com", industry: "Fintech", size: "1000+" },
  { name: "DoorDash", domain: "doordash.com", industry: "Logistics", size: "1000+" },
  { name: "Instacart", domain: "instacart.com", industry: "Logistics", size: "1000+" },
  { name: "Gusto", domain: "gusto.com", industry: "Fintech", size: "1000+" },
  { name: "Rippling", domain: "rippling.com", industry: "HR Tech", size: "1000+" },
  { name: "Carta", domain: "carta.com", industry: "Fintech", size: "1000+" },
  { name: "Brex", domain: "brex.com", industry: "Fintech", size: "1000+" },
  { name: "Ramp", domain: "ramp.com", industry: "Fintech", size: "1000+" },
  { name: "Chime", domain: "chime.com", industry: "Fintech", size: "1000+" },
  { name: "Robinhood", domain: "robinhood.com", industry: "Fintech", size: "1000+" },
  { name: "Coinbase", domain: "coinbase.com", industry: "Fintech", size: "1000+" },
  { name: "Plaid", domain: "plaid.com", industry: "Fintech", size: "1000+" },
  { name: "Affirm", domain: "affirm.com", industry: "Fintech", size: "1000+" },
  { name: "SoFi", domain: "sofi.com", industry: "Fintech", size: "1000+" },
  { name: "Klarna", domain: "klarna.com", industry: "Fintech", size: "1000+" },
  { name: "Wise", domain: "wise.com", industry: "Fintech", size: "1000+" },
  { name: "Xero", domain: "xero.com", industry: "Fintech", size: "1000+" },
  { name: "FreshBooks", domain: "freshbooks.com", industry: "Fintech", size: "201-500" },
  { name: "Bill.com", domain: "bill.com", industry: "Fintech", size: "1000+" },
  { name: "Anthropic", domain: "anthropic.com", industry: "AI", size: "201-500" },
  { name: "OpenAI", domain: "openai.com", industry: "AI", size: "1000+" },
  { name: "Hugging Face", domain: "huggingface.co", industry: "AI", size: "501-1000" },
  { name: "Cohere", domain: "cohere.com", industry: "AI", size: "201-500" },
  { name: "Scale AI", domain: "scale.com", industry: "AI", size: "1000+" },
  { name: "Mistral", domain: "mistral.ai", industry: "AI", size: "201-500" },
  { name: "DeepMind", domain: "deepmind.com", industry: "AI", size: "1000+" },
  { name: "Waymo", domain: "waymo.com", industry: "Autonomous", size: "1000+" },
  { name: "Cruise", domain: "getcruise.com", industry: "Autonomous", size: "1000+" },
  { name: "Tesla", domain: "tesla.com", industry: "Automotive", size: "1000+" },
  { name: "Rivian", domain: "rivian.com", industry: "Automotive", size: "1000+" },
  { name: "Lucid", domain: "lucidmotors.com", industry: "Automotive", size: "1000+" },
  { name: "Anduril", domain: "anduril.com", industry: "Defense", size: "1000+" },
  { name: "Booz Allen", domain: "boozallen.com", industry: "Consulting", size: "1000+" },
  { name: "Accenture", domain: "accenture.com", industry: "Consulting", size: "1000+" },
  { name: "McKinsey", domain: "mckinsey.com", industry: "Consulting", size: "1000+" },
  { name: "BCG", domain: "bcg.com", industry: "Consulting", size: "1000+" },
  { name: "Deloitte", domain: "deloitte.com", industry: "Consulting", size: "1000+" },
  { name: "KPMG", domain: "kpmg.com", industry: "Consulting", size: "1000+" },
  { name: "PwC", domain: "pwc.com", industry: "Consulting", size: "1000+" },
  { name: "EY", domain: "ey.com", industry: "Consulting", size: "1000+" },
  { name: "Etsy", domain: "etsy.com", industry: "E-commerce", size: "1000+" },
  { name: "eBay", domain: "ebay.com", industry: "E-commerce", size: "1000+" },
  { name: "Walmart Global Tech", domain: "walmart.com", industry: "Retail", size: "1000+" },
  { name: "Target", domain: "target.com", industry: "Retail", size: "1000+" },
  { name: "Costco", domain: "costco.com", industry: "Retail", size: "1000+" },
  { name: "Deliveroo", domain: "deliveroo.com", industry: "Logistics", size: "1000+" },
  { name: "Grubhub", domain: "grubhub.com", industry: "Logistics", size: "1000+" },
  { name: "Flexport", domain: "flexport.com", industry: "Logistics", size: "1000+" },
  { name: "Shippo", domain: "goshippo.com", industry: "Logistics", size: "201-500" },
  { name: "ShipBob", domain: "shipbob.com", industry: "Logistics", size: "1000+" },
  { name: "Postman", domain: "postman.com", industry: "Developer Tools", size: "1000+" },
  { name: "Sentry", domain: "sentry.io", industry: "Developer Tools", size: "1000+" },
  { name: "CircleCI", domain: "circleci.com", industry: "Developer Tools", size: "1000+" },
  { name: "Travis CI", domain: "travis-ci.com", industry: "Developer Tools", size: "201-500" },
  { name: "Circle", domain: "circle.com", industry: "Fintech", size: "1000+" },
  { name: "Binance", domain: "binance.com", industry: "Fintech", size: "1000+" },
  { name: "Kraken", domain: "kraken.com", industry: "Fintech", size: "1000+" },
  { name: "Duolingo", domain: "duolingo.com", industry: "Consumer", size: "1000+" },
  { name: "Khan Academy", domain: "khanacademy.org", industry: "Education", size: "201-500" },
  { name: "Coursera", domain: "coursera.org", industry: "Education", size: "1000+" },
  { name: "Udemy", domain: "udemy.com", industry: "Education", size: "1000+" },
  { name: "Udacity", domain: "udacity.com", industry: "Education", size: "201-500" },
  { name: "Skillshare", domain: "skillshare.com", industry: "Education", size: "201-500" },
  { name: "Quizlet", domain: "quizlet.com", industry: "Education", size: "201-500" },
  { name: "Chegg", domain: "chegg.com", industry: "Education", size: "1000+" },
  { name: "Airbyte", domain: "airbyte.com", industry: "Data", size: "501-1000" },
  { name: "RudderStack", domain: "rudderstack.com", industry: "Data", size: "201-500" },
  { name: "Abnormal Security", domain: "abnormalsecurity.com", industry: "Security", size: "1000+" },
  { name: "SentinelOne", domain: "sentinelone.com", industry: "Security", size: "1000+" },
  { name: "Rapid7", domain: "rapid7.com", industry: "Security", size: "1000+" },
  { name: "DuckDuckGo", domain: "duckduckgo.com", industry: "Consumer", size: "201-500" },
  { name: "Mozilla", domain: "mozilla.org", industry: "Consumer", size: "1000+" },
  { name: "Pinterest", domain: "pinterest.com", industry: "Consumer", size: "1000+" },
  { name: "Snap", domain: "snap.com", industry: "Consumer", size: "1000+" },
  { name: "TikTok", domain: "tiktok.com", industry: "Consumer", size: "1000+" },
  { name: "ByteDance", domain: "bytedance.com", industry: "Consumer", size: "1000+" },
  { name: "Reddit", domain: "reddit.com", industry: "Consumer", size: "1000+" },
  { name: "Spotify", domain: "spotify.com", industry: "Media", size: "1000+" },
  { name: "SoundCloud", domain: "soundcloud.com", industry: "Media", size: "201-500" },
  { name: "Twitch", domain: "twitch.tv", industry: "Media", size: "1000+" },
  { name: "Roblox", domain: "roblox.com", industry: "Gaming", size: "1000+" },
  { name: "Epic Games", domain: "epicgames.com", industry: "Gaming", size: "1000+" },
  { name: "Unity", domain: "unity.com", industry: "Gaming", size: "1000+" },
  { name: "Niantic", domain: "nianticlabs.com", industry: "Gaming", size: "501-1000" },
  { name: "Electronic Arts", domain: "ea.com", industry: "Gaming", size: "1000+" },
  { name: "Activision Blizzard", domain: "activisionblizzard.com", industry: "Gaming", size: "1000+" },
  { name: "Zynga", domain: "zynga.com", industry: "Gaming", size: "1000+" },
  { name: "Riot Games", domain: "riotgames.com", industry: "Gaming", size: "1000+" },
  { name: "LinkedIn", domain: "linkedin.com", industry: "Social", size: "1000+" },
  { name: "X (Twitter)", domain: "x.com", industry: "Social", size: "1000+" },
  { name: "Stack Overflow", domain: "stackoverflow.com", industry: "Developer Tools", size: "1000+" },
  { name: "StackBlitz", domain: "stackblitz.com", industry: "Developer Tools", size: "201-500" },
  { name: "Replit", domain: "replit.com", industry: "Developer Tools", size: "201-500" },
  { name: "CodeSandbox", domain: "codesandbox.io", industry: "Developer Tools", size: "201-500" },
  { name: "Glitch", domain: "glitch.com", industry: "Developer Tools", size: "201-500" },
  { name: "JetBrains", domain: "jetbrains.com", industry: "Developer Tools", size: "1000+" },
  { name: "PostgresPro", domain: "postgrespro.com", industry: "Data", size: "201-500" },
  { name: "Red Hat", domain: "redhat.com", industry: "Infrastructure", size: "1000+" },
  { name: "Canonical", domain: "canonical.com", industry: "Infrastructure", size: "1000+" },
  { name: "SUSE", domain: "suse.com", industry: "Infrastructure", size: "1000+" },
  { name: "Cloudera", domain: "cloudera.com", industry: "Data", size: "1000+" },
  { name: "Alteryx", domain: "alteryx.com", industry: "Analytics", size: "1000+" },
  { name: "Datastudio", domain: "datastudio.google.com", industry: "Analytics", size: "1000+" },
  { name: "Databricks Labs", domain: "databricks.com", industry: "Data", size: "1000+" },
  { name: "Cloudinary", domain: "cloudinary.com", industry: "Developer Tools", size: "1000+" },
  { name: "Algolia", domain: "algolia.com", industry: "Developer Tools", size: "1000+" },
  { name: "Okta Customer Identity", domain: "okta.com", industry: "Security", size: "1000+" },
  { name: "OneLogin", domain: "onelogin.com", industry: "Security", size: "501-1000" },
  { name: "ForgeRock", domain: "forgerock.com", industry: "Security", size: "1000+" },
  { name: "Ping Identity", domain: "pingidentity.com", industry: "Security", size: "1000+" },
  { name: "Fortinet", domain: "fortinet.com", industry: "Security", size: "1000+" },
  { name: "Check Point", domain: "checkpoint.com", industry: "Security", size: "1000+" },
  { name: "Tanium", domain: "tanium.com", industry: "Security", size: "1000+" },
  { name: "Illumio", domain: "illumio.com", industry: "Security", size: "1000+" },
  { name: "Darktrace", domain: "darktrace.com", industry: "Security", size: "1000+" },
  { name: "Rubrik", domain: "rubrik.com", industry: "Security", size: "1000+" },
  { name: "Cohesity", domain: "cohesity.com", industry: "Security", size: "1000+" },
  { name: "NetApp", domain: "netapp.com", industry: "Infrastructure", size: "1000+" },
  { name: "Pure Storage", domain: "purestorage.com", industry: "Infrastructure", size: "1000+" },
  { name: "Seagate", domain: "seagate.com", industry: "Hardware", size: "1000+" },
  { name: "Western Digital", domain: "westerndigital.com", industry: "Hardware", size: "1000+" },
  { name: "Samsung", domain: "samsung.com", industry: "Consumer Tech", size: "1000+" },
  { name: "Sony", domain: "sony.com", industry: "Consumer Tech", size: "1000+" },
  { name: "LG", domain: "lg.com", industry: "Consumer Tech", size: "1000+" },
  { name: "Panasonic", domain: "panasonic.com", industry: "Consumer Tech", size: "1000+" },
  { name: "Philips", domain: "philips.com", industry: "Consumer Tech", size: "1000+" },
  { name: "Siemens", domain: "siemens.com", industry: "Industrial", size: "1000+" },
  { name: "GE", domain: "ge.com", industry: "Industrial", size: "1000+" },
  { name: "Honeywell", domain: "honeywell.com", industry: "Industrial", size: "1000+" },
  { name: "Schneider Electric", domain: "se.com", industry: "Industrial", size: "1000+" },
  { name: "Rockwell Automation", domain: "rockwellautomation.com", industry: "Industrial", size: "1000+" },
  { name: "Bosch", domain: "bosch.com", industry: "Industrial", size: "1000+" },
  { name: "Boeing", domain: "boeing.com", industry: "Aerospace", size: "1000+" },
  { name: "Airbus", domain: "airbus.com", industry: "Aerospace", size: "1000+" },
  { name: "SpaceX", domain: "spacex.com", industry: "Aerospace", size: "1000+" },
  { name: "Blue Origin", domain: "blueorigin.com", industry: "Aerospace", size: "1000+" },
  { name: "Lockheed Martin", domain: "lockheedmartin.com", industry: "Defense", size: "1000+" },
  { name: "Raytheon", domain: "rtx.com", industry: "Defense", size: "1000+" },
  { name: "Northrop Grumman", domain: "northropgrumman.com", industry: "Defense", size: "1000+" },
  { name: "BAE Systems", domain: "baesystems.com", industry: "Defense", size: "1000+" },
  { name: "Palantir Foundry", domain: "palantir.com", industry: "Data", size: "1000+" },
  { name: "Snowflake Cortex", domain: "snowflake.com", industry: "Data", size: "1000+" },
  { name: "Stripe Climate", domain: "stripe.com", industry: "Fintech", size: "1000+" },
  { name: "Mercury", domain: "mercury.com", industry: "Fintech", size: "201-500" },
  { name: "Plaid Signal", domain: "plaid.com", industry: "Fintech", size: "1000+" },
  { name: "Finix", domain: "finix.com", industry: "Fintech", size: "201-500" },
  { name: "Marqeta", domain: "marqeta.com", industry: "Fintech", size: "1000+" },
  { name: "Checkout.com", domain: "checkout.com", industry: "Fintech", size: "1000+" },
  { name: "Adyen", domain: "adyen.com", industry: "Fintech", size: "1000+" },
  { name: "Visa", domain: "visa.com", industry: "Fintech", size: "1000+" },
  { name: "Mastercard", domain: "mastercard.com", industry: "Fintech", size: "1000+" },
  { name: "American Express", domain: "americanexpress.com", industry: "Fintech", size: "1000+" },
  { name: "Capital One", domain: "capitalone.com", industry: "Fintech", size: "1000+" },
  { name: "JPMorgan", domain: "jpmorganchase.com", industry: "Fintech", size: "1000+" },
  { name: "Goldman Sachs", domain: "goldmansachs.com", industry: "Fintech", size: "1000+" },
  { name: "Morgan Stanley", domain: "morganstanley.com", industry: "Fintech", size: "1000+" },
  { name: "BlackRock", domain: "blackrock.com", industry: "Fintech", size: "1000+" },
  { name: "Fidelity", domain: "fidelity.com", industry: "Fintech", size: "1000+" },
  { name: "Vanguard", domain: "vanguard.com", industry: "Fintech", size: "1000+" },
  { name: "American Airlines", domain: "aa.com", industry: "Travel", size: "1000+" },
  { name: "Delta", domain: "delta.com", industry: "Travel", size: "1000+" },
  { name: "United Airlines", domain: "united.com", industry: "Travel", size: "1000+" },
  { name: "Southwest", domain: "southwest.com", industry: "Travel", size: "1000+" },
  { name: "Booking.com", domain: "booking.com", industry: "Travel", size: "1000+" },
  { name: "Expedia", domain: "expedia.com", industry: "Travel", size: "1000+" },
  { name: "Priceline", domain: "priceline.com", industry: "Travel", size: "1000+" },
  { name: "Tripadvisor", domain: "tripadvisor.com", industry: "Travel", size: "1000+" },
  { name: "Kayak", domain: "kayak.com", industry: "Travel", size: "1000+" },
  { name: "Marriott", domain: "marriott.com", industry: "Travel", size: "1000+" },
  { name: "Hilton", domain: "hilton.com", industry: "Travel", size: "1000+" },
  { name: "IHG", domain: "ihg.com", industry: "Travel", size: "1000+" },
  { name: "UnitedHealth", domain: "uhc.com", industry: "Healthcare", size: "1000+" },
  { name: "CVS Health", domain: "cvs.com", industry: "Healthcare", size: "1000+" },
  { name: "Kaiser Permanente", domain: "kp.org", industry: "Healthcare", size: "1000+" },
  { name: "Cerner", domain: "cerner.com", industry: "Healthcare", size: "1000+" },
  { name: "Epic Systems", domain: "epic.com", industry: "Healthcare", size: "1000+" },
  { name: "Teladoc", domain: "teladoc.com", industry: "Healthcare", size: "1000+" },
  { name: "One Medical", domain: "onemedical.com", industry: "Healthcare", size: "1000+" },
  { name: "Verizon", domain: "verizon.com", industry: "Telecom", size: "1000+" },
  { name: "AT&T", domain: "att.com", industry: "Telecom", size: "1000+" },
  { name: "T-Mobile", domain: "t-mobile.com", industry: "Telecom", size: "1000+" },
  { name: "Comcast", domain: "comcast.com", industry: "Telecom", size: "1000+" },
  { name: "Charter", domain: "charter.com", industry: "Telecom", size: "1000+" },
  { name: "BT", domain: "bt.com", industry: "Telecom", size: "1000+" },
  { name: "Vodafone", domain: "vodafone.com", industry: "Telecom", size: "1000+" },
  { name: "Ericsson", domain: "ericsson.com", industry: "Telecom", size: "1000+" },
  { name: "Nokia", domain: "nokia.com", industry: "Telecom", size: "1000+" },
  { name: "Shopify Plus", domain: "shopify.com", industry: "E-commerce", size: "1000+" },
  { name: "Wayfair", domain: "wayfair.com", industry: "E-commerce", size: "1000+" },
  { name: "Chewy", domain: "chewy.com", industry: "E-commerce", size: "1000+" },
  { name: "Zillow", domain: "zillow.com", industry: "Real Estate", size: "1000+" },
  { name: "Redfin", domain: "redfin.com", industry: "Real Estate", size: "1000+" },
  { name: "Opendoor", domain: "opendoor.com", industry: "Real Estate", size: "1000+" },
  { name: "Compass", domain: "compass.com", industry: "Real Estate", size: "1000+" },
  { name: "WeWork", domain: "wework.com", industry: "Real Estate", size: "1000+" },
  { name: "SquareSpace", domain: "squarespace.com", industry: "SaaS", size: "1000+" },
  { name: "Wix", domain: "wix.com", industry: "SaaS", size: "1000+" },
  { name: "WordPress.com", domain: "wordpress.com", industry: "SaaS", size: "1000+" },
  { name: "Automattic", domain: "automattic.com", industry: "SaaS", size: "1000+" },
  { name: "GitKraken", domain: "gitkraken.com", industry: "Developer Tools", size: "201-500" },
  { name: "HashiCorp Terraform", domain: "hashicorp.com", industry: "Infrastructure", size: "1000+" },
  { name: "Docker", domain: "docker.com", industry: "Developer Tools", size: "1000+" },
  { name: "Kubernetes", domain: "kubernetes.io", industry: "Developer Tools", size: "1000+" },
  { name: "Chef", domain: "chef.io", industry: "Infrastructure", size: "201-500" },
  { name: "Puppet", domain: "puppet.com", industry: "Infrastructure", size: "201-500" },
  { name: "Ansible", domain: "ansible.com", industry: "Infrastructure", size: "201-500" },
  { name: "Grafana Labs", domain: "grafana.com", industry: "Developer Tools", size: "1000+" },
  { name: "Prometheus", domain: "prometheus.io", industry: "Developer Tools", size: "1000+" },
  { name: "OpenTelemetry", domain: "opentelemetry.io", industry: "Developer Tools", size: "1000+" },
  { name: "Elastic Cloud", domain: "elastic.co", industry: "Data", size: "1000+" },
  { name: "HackerOne", domain: "hackerone.com", industry: "Security", size: "201-500" },
  { name: "Bugcrowd", domain: "bugcrowd.com", industry: "Security", size: "201-500" },
  { name: "GitGuardian", domain: "gitguardian.com", industry: "Security", size: "201-500" },
  { name: "Snyk Labs", domain: "snyk.io", industry: "Security", size: "1000+" },
  { name: "Nutanix", domain: "nutanix.com", industry: "Infrastructure", size: "1000+" },
  { name: "Citrix", domain: "citrix.com", industry: "Infrastructure", size: "1000+" },
  { name: "F5", domain: "f5.com", industry: "Networking", size: "1000+" },
  { name: "Juniper Networks", domain: "juniper.net", industry: "Networking", size: "1000+" },
  { name: "Arista Networks", domain: "arista.com", industry: "Networking", size: "1000+" },
  { name: "Netgear", domain: "netgear.com", industry: "Networking", size: "1000+" },
  { name: "Cloudflare Workers", domain: "cloudflare.com", industry: "Infrastructure", size: "1000+" },
  { name: "Fastly Compute", domain: "fastly.com", industry: "Infrastructure", size: "1000+" },
  { name: "Okta Workforce", domain: "okta.com", industry: "Security", size: "1000+" },
  { name: "Snowflake Data Cloud", domain: "snowflake.com", industry: "Data", size: "1000+" },
  { name: "Databricks Mosaic", domain: "databricks.com", industry: "AI", size: "1000+" },
  { name: "NVIDIA Omniverse", domain: "nvidia.com", industry: "AI", size: "1000+" },
  { name: "Adobe Experience", domain: "adobe.com", industry: "Marketing", size: "1000+" },
  { name: "Salesforce Data Cloud", domain: "salesforce.com", industry: "Enterprise Software", size: "1000+" },
  { name: "ServiceNow Platform", domain: "servicenow.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Workday Financials", domain: "workday.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Asana Enterprise", domain: "asana.com", industry: "Productivity", size: "1000+" },
  { name: "Monday Enterprise", domain: "monday.com", industry: "Productivity", size: "1000+" },
  { name: "OpenSea", domain: "opensea.io", industry: "Fintech", size: "201-500" },
  { name: "Dapper Labs", domain: "dapperlabs.com", industry: "Fintech", size: "201-500" },
  { name: "Polygon", domain: "polygon.technology", industry: "Fintech", size: "201-500" },
  { name: "Chainalysis", domain: "chainalysis.com", industry: "Fintech", size: "501-1000" },
  { name: "ConsenSys", domain: "consensys.net", industry: "Fintech", size: "501-1000" },
  { name: "OKX", domain: "okx.com", industry: "Fintech", size: "1000+" },
  { name: "Coinbase Commerce", domain: "coinbase.com", industry: "Fintech", size: "1000+" },
  { name: "Bitstamp", domain: "bitstamp.net", industry: "Fintech", size: "501-1000" },
  { name: "Bitfinex", domain: "bitfinex.com", industry: "Fintech", size: "1000+" },
  { name: "Stripe Atlas", domain: "stripe.com", industry: "Fintech", size: "1000+" },
  { name: "Payoneer", domain: "payoneer.com", industry: "Fintech", size: "1000+" },
  { name: "PayU", domain: "payu.com", industry: "Fintech", size: "1000+" },
  { name: "Remitly", domain: "remitly.com", industry: "Fintech", size: "1000+" },
  { name: "N26", domain: "n26.com", industry: "Fintech", size: "1000+" },
  { name: "Monzo", domain: "monzo.com", industry: "Fintech", size: "1000+" },
  { name: "Revolut", domain: "revolut.com", industry: "Fintech", size: "1000+" },
  { name: "Wise Business", domain: "wise.com", industry: "Fintech", size: "1000+" },
  { name: "Shopify Payments", domain: "shopify.com", industry: "Fintech", size: "1000+" },
  { name: "Shopify POS", domain: "shopify.com", industry: "Fintech", size: "1000+" },
  { name: "Klaviyo", domain: "klaviyo.com", industry: "Marketing", size: "1000+" },
  { name: "Mailchimp", domain: "mailchimp.com", industry: "Marketing", size: "1000+" },
  { name: "SendGrid", domain: "sendgrid.com", industry: "Marketing", size: "1000+" },
  { name: "Customer.io", domain: "customer.io", industry: "Marketing", size: "201-500" },
  { name: "Iterable", domain: "iterable.com", industry: "Marketing", size: "1000+" },
  { name: "Twilio Segment", domain: "segment.com", industry: "Marketing", size: "1000+" },
  { name: "Kustomer", domain: "kustomer.com", industry: "SaaS", size: "1000+" },
  { name: "Gainsight", domain: "gainsight.com", industry: "SaaS", size: "1000+" },
  { name: "Outreach", domain: "outreach.io", industry: "SaaS", size: "1000+" },
  { name: "Clari", domain: "clari.com", industry: "SaaS", size: "1000+" },
  { name: "Gong", domain: "gong.io", industry: "SaaS", size: "1000+" },
  { name: "DocuSign", domain: "docusign.com", industry: "SaaS", size: "1000+" },
  { name: "Okta Verify", domain: "okta.com", industry: "Security", size: "1000+" },
  { name: "Splunk Observability", domain: "splunk.com", industry: "Data", size: "1000+" },
  { name: "Datadog APM", domain: "datadoghq.com", industry: "Infrastructure", size: "1000+" },
  { name: "Grafana Cloud", domain: "grafana.com", industry: "Developer Tools", size: "1000+" },
  { name: "Zabbix", domain: "zabbix.com", industry: "Infrastructure", size: "201-500" },
  { name: "Pingdom", domain: "pingdom.com", industry: "Infrastructure", size: "201-500" },
  { name: "SolarWinds", domain: "solarwinds.com", industry: "Infrastructure", size: "1000+" },
  { name: "New Relic One", domain: "newrelic.com", industry: "Infrastructure", size: "1000+" },
  { name: "PagerDuty Ops", domain: "pagerduty.com", industry: "Infrastructure", size: "1000+" },
  { name: "Veeam", domain: "veeam.com", industry: "Infrastructure", size: "1000+" },
  { name: "Atlassian Jira", domain: "atlassian.com", industry: "Productivity", size: "1000+" },
  { name: "Atlassian Confluence", domain: "atlassian.com", industry: "Productivity", size: "1000+" },
  { name: "Notion AI", domain: "notion.so", industry: "Productivity", size: "1000+" },
  { name: "Miro AI", domain: "miro.com", industry: "Productivity", size: "1000+" },
  { name: "Airtable AI", domain: "airtable.com", industry: "Productivity", size: "1000+" },
  { name: "Zoom AI", domain: "zoom.us", industry: "Productivity", size: "1000+" },
  { name: "Box Sign", domain: "box.com", industry: "SaaS", size: "1000+" },
  { name: "Dropbox Sign", domain: "dropbox.com", industry: "SaaS", size: "1000+" },
  { name: "Notion Calendar", domain: "notion.so", industry: "Productivity", size: "1000+" },
  { name: "Asana AI", domain: "asana.com", industry: "Productivity", size: "1000+" },
  { name: "Coda AI", domain: "coda.io", industry: "Productivity", size: "201-500" },
  { name: "Miro Enterprise", domain: "miro.com", industry: "Productivity", size: "1000+" },
  { name: "Figma FigJam", domain: "figma.com", industry: "Design", size: "1000+" },
  { name: "Sketch", domain: "sketch.com", industry: "Design", size: "201-500" },
  { name: "InVision", domain: "invisionapp.com", industry: "Design", size: "201-500" },
  { name: "Framer", domain: "framer.com", industry: "Design", size: "201-500" },
  { name: "Webflow", domain: "webflow.com", industry: "Design", size: "1000+" },
  { name: "Squarespace", domain: "squarespace.com", industry: "SaaS", size: "1000+" },
  { name: "Elementor", domain: "elementor.com", industry: "SaaS", size: "201-500" },
  { name: "Dribbble", domain: "dribbble.com", industry: "Design", size: "201-500" },
  { name: "Behance", domain: "behance.net", industry: "Design", size: "1000+" },
  { name: "Adobe Creative Cloud", domain: "adobe.com", industry: "Design", size: "1000+" },
  { name: "Canva Teams", domain: "canva.com", industry: "Design", size: "1000+" },
  { name: "Figma Enterprise", domain: "figma.com", industry: "Design", size: "1000+" },
  { name: "Notion Enterprise", domain: "notion.so", industry: "Productivity", size: "1000+" },
];

const extraCompanySeed: CompanySeed[] = [
  { name: "Hulu", domain: "hulu.com", industry: "Media", size: "1000+" },
  { name: "Disney", domain: "disney.com", industry: "Media", size: "1000+" },
  { name: "Warner Bros", domain: "wbd.com", industry: "Media", size: "1000+" },
  { name: "Paramount", domain: "paramount.com", industry: "Media", size: "1000+" },
  { name: "BBC", domain: "bbc.com", industry: "Media", size: "1000+" },
  { name: "New York Times", domain: "nytimes.com", industry: "Media", size: "1000+" },
  { name: "The Washington Post", domain: "washingtonpost.com", industry: "Media", size: "1000+" },
  { name: "Bloomberg", domain: "bloomberg.com", industry: "Media", size: "1000+" },
  { name: "Thomson Reuters", domain: "tr.com", industry: "Media", size: "1000+" },
  { name: "Stripe Press", domain: "stripe.com", industry: "Media", size: "1000+" },
  { name: "Instabase", domain: "instabase.com", industry: "AI", size: "201-500" },
  { name: "Scale AI Data", domain: "scale.com", industry: "AI", size: "1000+" },
  { name: "OpenAI Platform", domain: "openai.com", industry: "AI", size: "1000+" },
  { name: "Anthropic Claude", domain: "anthropic.com", industry: "AI", size: "201-500" },
  { name: "Cohere Platform", domain: "cohere.com", industry: "AI", size: "201-500" },
  { name: "Mistral API", domain: "mistral.ai", industry: "AI", size: "201-500" },
  { name: "Hugging Face Hub", domain: "huggingface.co", industry: "AI", size: "501-1000" },
  { name: "H2O.ai", domain: "h2o.ai", industry: "AI", size: "201-500" },
  { name: "DataRobot", domain: "datarobot.com", industry: "AI", size: "1000+" },
  { name: "C3.ai", domain: "c3.ai", industry: "AI", size: "1000+" },
  { name: "UiPath Automation", domain: "uipath.com", industry: "Automation", size: "1000+" },
  { name: "Blue Prism", domain: "blueprism.com", industry: "Automation", size: "1000+" },
  { name: "Automation Anywhere Cloud", domain: "automationanywhere.com", industry: "Automation", size: "1000+" },
  { name: "Workato Connectors", domain: "workato.com", industry: "Automation", size: "1000+" },
  { name: "Zapier Interfaces", domain: "zapier.com", industry: "Automation", size: "1000+" },
  { name: "IFTTT Pro", domain: "ifttt.com", industry: "Automation", size: "51-200" },
  { name: "Fivetran Connectors", domain: "fivetran.com", industry: "Data", size: "1000+" },
  { name: "Airbyte Cloud", domain: "airbyte.com", industry: "Data", size: "501-1000" },
  { name: "RudderStack Cloud", domain: "rudderstack.com", industry: "Data", size: "201-500" },
  { name: "Segment Connections", domain: "segment.com", industry: "Data", size: "1000+" },
  { name: "Snowflake Marketplace", domain: "snowflake.com", industry: "Data", size: "1000+" },
  { name: "Databricks Marketplace", domain: "databricks.com", industry: "Data", size: "1000+" },
  { name: "Datadog Logs", domain: "datadoghq.com", industry: "Infrastructure", size: "1000+" },
  { name: "Datadog Security", domain: "datadoghq.com", industry: "Security", size: "1000+" },
  { name: "Sentry Performance", domain: "sentry.io", industry: "Developer Tools", size: "1000+" },
  { name: "PagerDuty Rundeck", domain: "pagerduty.com", industry: "Infrastructure", size: "1000+" },
  { name: "Splunk SOAR", domain: "splunk.com", industry: "Security", size: "1000+" },
  { name: "CrowdStrike Falcon", domain: "crowdstrike.com", industry: "Security", size: "1000+" },
  { name: "Zscaler Zero Trust", domain: "zscaler.com", industry: "Security", size: "1000+" },
  { name: "Palo Alto Prisma", domain: "paloaltonetworks.com", industry: "Security", size: "1000+" },
  { name: "Okta Workforce", domain: "okta.com", industry: "Security", size: "1000+" },
  { name: "Auth0 CIAM", domain: "auth0.com", industry: "Security", size: "1000+" },
  { name: "Databricks Unity Catalog", domain: "databricks.com", industry: "Data", size: "1000+" },
  { name: "Snowflake Snowpark", domain: "snowflake.com", industry: "Data", size: "1000+" },
  { name: "AWS", domain: "aws.amazon.com", industry: "Cloud", size: "1000+" },
  { name: "Azure", domain: "azure.microsoft.com", industry: "Cloud", size: "1000+" },
  { name: "Google Cloud", domain: "cloud.google.com", industry: "Cloud", size: "1000+" },
  { name: "Oracle Cloud", domain: "oracle.com", industry: "Cloud", size: "1000+" },
  { name: "IBM Cloud", domain: "ibm.com", industry: "Cloud", size: "1000+" },
  { name: "Alibaba Cloud", domain: "alibabacloud.com", industry: "Cloud", size: "1000+" },
  { name: "Tencent Cloud", domain: "cloud.tencent.com", industry: "Cloud", size: "1000+" },
  { name: "SAP Cloud", domain: "sap.com", industry: "Cloud", size: "1000+" },
  { name: "Oracle NetSuite", domain: "netsuite.com", industry: "Enterprise Software", size: "1000+" },
  { name: "ServiceNow ITSM", domain: "servicenow.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Salesforce Sales Cloud", domain: "salesforce.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Salesforce Service Cloud", domain: "salesforce.com", industry: "Enterprise Software", size: "1000+" },
  { name: "HubSpot CRM", domain: "hubspot.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Zendesk Support", domain: "zendesk.com", industry: "Enterprise Software", size: "1000+" },
  { name: "Intercom Messenger", domain: "intercom.com", industry: "SaaS", size: "1000+" },
  { name: "Gong Revenue", domain: "gong.io", industry: "SaaS", size: "1000+" },
  { name: "Snowflake Cortex AI", domain: "snowflake.com", industry: "AI", size: "1000+" },
  { name: "Databricks AI", domain: "databricks.com", industry: "AI", size: "1000+" },
  { name: "Vercel Edge", domain: "vercel.com", industry: "Developer Tools", size: "501-1000" },
  { name: "Netlify Edge", domain: "netlify.com", industry: "Developer Tools", size: "501-1000" },
  { name: "Cloudflare Pages", domain: "cloudflare.com", industry: "Developer Tools", size: "1000+" },
  { name: "Fastly CDN", domain: "fastly.com", industry: "Infrastructure", size: "1000+" },
  { name: "Akamai CDN", domain: "akamai.com", industry: "Infrastructure", size: "1000+" },
  { name: "Stripe Terminal", domain: "stripe.com", industry: "Fintech", size: "1000+" },
  { name: "Brex Empower", domain: "brex.com", industry: "Fintech", size: "1000+" },
  { name: "Ramp Treasury", domain: "ramp.com", industry: "Fintech", size: "1000+" },
  { name: "Plaid Link", domain: "plaid.com", industry: "Fintech", size: "1000+" },
  { name: "Chime Banking", domain: "chime.com", industry: "Fintech", size: "1000+" },
  { name: "Gusto Payroll", domain: "gusto.com", industry: "Fintech", size: "1000+" },
  { name: "Rippling IT", domain: "rippling.com", industry: "HR Tech", size: "1000+" },
  { name: "Carta Equity", domain: "carta.com", industry: "Fintech", size: "1000+" },
  { name: "Klarna Checkout", domain: "klarna.com", industry: "Fintech", size: "1000+" },
  { name: "Shopify Fulfillment", domain: "shopify.com", industry: "Logistics", size: "1000+" },
  { name: "ShipBob Fulfillment", domain: "shipbob.com", industry: "Logistics", size: "1000+" },
  { name: "Flexport Logistics", domain: "flexport.com", industry: "Logistics", size: "1000+" },
  { name: "DoorDash Drive", domain: "doordash.com", industry: "Logistics", size: "1000+" },
  { name: "Instacart Connect", domain: "instacart.com", industry: "Logistics", size: "1000+" },
  { name: "Grubhub Corporate", domain: "grubhub.com", industry: "Logistics", size: "1000+" },
  { name: "Wayfair Logistics", domain: "wayfair.com", industry: "Logistics", size: "1000+" },
  { name: "Chewy Pharmacy", domain: "chewy.com", industry: "E-commerce", size: "1000+" },
];

const industries = [
  "SaaS",
  "Fintech",
  "AI",
  "Cloud",
  "Security",
  "Data",
  "Infrastructure",
  "Developer Tools",
  "Healthcare",
  "E-commerce",
  "Logistics",
  "Enterprise Software",
  "Consumer",
  "Media",
  "Education",
  "Gaming",
];

const sizeBands = ["51-200", "201-500", "501-1000", "1000+"];

const synthPrefixes = [
  "Apex",
  "Ardent",
  "Atlas",
  "Aurora",
  "Beacon",
  "Bright",
  "Cascade",
  "Civic",
  "Clarity",
  "Cloud",
  "Cobalt",
  "Core",
  "Crimson",
  "Crown",
  "Crystal",
  "Echo",
  "Elevate",
  "Ember",
  "Ever",
  "Falcon",
  "Flux",
  "Forge",
  "Frontier",
  "Fusion",
  "Glide",
  "Graph",
  "Halo",
  "Harbor",
  "Horizon",
  "Hyper",
  "Ignite",
  "Infini",
  "Ion",
  "Juno",
  "Kinetic",
  "Lattice",
  "Launch",
  "Lumen",
  "Lunar",
  "Magnet",
  "Meridian",
  "Meta",
  "Momentum",
  "Monarch",
  "Nexus",
  "Nimbus",
  "Nova",
  "Obsidian",
  "Omni",
  "Orbit",
  "Origin",
  "Pioneer",
  "Pixel",
  "Prime",
  "Pulse",
  "Quantum",
  "Quasar",
  "Radial",
  "Radiant",
  "Redwood",
  "Relay",
  "Signal",
  "Silver",
  "Sky",
  "Solace",
  "Solar",
  "Spark",
  "Spectra",
  "Summit",
  "Synergy",
  "Terra",
  "Tidal",
  "Trident",
  "Unity",
  "Vertex",
  "Vista",
  "Vivid",
  "Voyage",
  "Wave",
  "Zen",
];

const synthSuffixes = [
  "Labs",
  "Systems",
  "Works",
  "Cloud",
  "Data",
  "AI",
  "Security",
  "Health",
  "Logic",
  "Tech",
  "Networks",
  "Automation",
  "Analytics",
  "Platforms",
  "Ops",
  "Stack",
  "Dynamics",
  "Solutions",
  "Studio",
  "Engineering",
  "Soft",
  "Ware",
  "Digital",
  "Group",
];

const buildSyntheticCompanies = (targetCount: number) => {
  const companies: CompanySeed[] = [];
  const existing = new Set<string>([...baseCompanySeed, ...extraCompanySeed].map((item) => item.name.toLowerCase()));
  let index = 0;
  while (companies.length < targetCount && index < synthPrefixes.length * synthSuffixes.length) {
    const prefix = synthPrefixes[index % synthPrefixes.length];
    const suffix = synthSuffixes[Math.floor(index / synthPrefixes.length) % synthSuffixes.length];
    const name = `${prefix} ${suffix}`;
    index += 1;
    if (existing.has(name.toLowerCase())) continue;
    const domain = `${prefix}${suffix}`.toLowerCase().replace(/[^a-z0-9]/g, "") + ".com";
    const industry = industries[index % industries.length];
    const size = sizeBands[index % sizeBands.length];
    companies.push({ name, domain, industry, size });
  }
  return companies;
};

const combined = [...baseCompanySeed, ...extraCompanySeed];
const syntheticCompanySeed = buildSyntheticCompanies(Math.max(0, 1000 - combined.length));

export const companySeed: CompanySeed[] = [...combined, ...syntheticCompanySeed].slice(0, 1000);
