import type { LeadAnswers } from "@/lib/validation";

export const defaultAnswers: LeadAnswers = {
  roles: [],
  currentTitle: "",
  experienceYears: "6-9",
  leadershipScope: "IC",
  level: "Senior",
  compTarget: "150k-200k",
  compensationPriority: "Balanced",
  timeline: "30",
  locationType: "Remote",
  city: "",
  targetIndustry: "B2B SaaS",
  companyStage: "Growth",
  hoursPerWeek: "5",
  assets: { resume: "Draft", linkedin: "Draft", interview: "Some practice", portfolio: "Some" },
  linkedinUrl: "",
  linkedinHeadline: "",
  linkedinSummary: "",
  resumeText: "",
  resumeUploaded: false,
  networkStrength: "Medium",
  outreachComfort: "Medium",
  companyTargets: [],
  constraints: [],
  biggestBlocker: "Not getting responses",
  blockerNote: "",
  coachFeedback: "",
  pipeline: "Some",
};
