import type { AssessmentAnswers } from "@/lib/validation";

export const defaultAnswers: AssessmentAnswers = {
  targetRoles: [],
  level: "Senior",
  compTarget: "$150k-$200k",
  timeline: "1-2 months",
  locationPreference: "Remote",
  locationCity: "",
  hoursPerWeek: 5,
  resumeStatus: "needs_work",
  linkedinStatus: "basic",
  portfolioStatus: false,
  interviewReady: false,
  resumeFileUrl: null,
  resumeFileName: null,
  resumeFileSize: null,
  linkedinFileUrl: null,
  linkedinFileName: null,
  networkStrength: "moderate",
  outreachComfort: "neutral",
  targetCompanies: [],
  biggestBlocker: "responses",
  additionalContext: "",
};
