import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = process.env.NEXT_PUBLIC_BASE_URL || "https://zaricoach.com";
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    // Core marketing
    { url: base,                                    lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${base}/platform`,                      lastModified: now, changeFrequency: "weekly",  priority: 0.95 },
    { url: `${base}/pricing`,                       lastModified: now, changeFrequency: "weekly",  priority: 0.95 },
    { url: `${base}/use-cases`,                     lastModified: now, changeFrequency: "monthly", priority: 0.9 },

    // Primary keyword landing pages (highest SEO priority)
    { url: `${base}/ai-career-coach`,               lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${base}/ai-resume-writer`,              lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${base}/ai-interview-coach`,            lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${base}/ai-linkedin-optimizer`,         lastModified: now, changeFrequency: "weekly",  priority: 0.95 },

    // Career coach variants
    { url: `${base}/career-coach-tool`,             lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/personal-career-coach`,         lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/free-career-coach`,             lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/career-coaching-software`,      lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Specialty coaching
    { url: `${base}/salary-negotiation-coach`,      lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/promotion-coach`,               lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/career-change-coach`,           lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Service pages
    { url: `${base}/resume-review-service`,         lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/cover-letter-writer`,           lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/linkedin-profile-optimization`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/job-interview-preparation`,     lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Free tool pages (high bottom-of-funnel SEO)
    { url: `${base}/free-resume-checker`,           lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/free-ats-checker`,              lastModified: now, changeFrequency: "monthly", priority: 0.9 },

    // Profession-specific career coaching
    { url: `${base}/career-coach-for-software-engineers`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-product-managers`,   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-executives`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-nurses`,                      lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-teachers`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-marketing-professionals`,     lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-data-scientists`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-finance-professionals`,       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-sales-professionals`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-designers`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-hr-professionals`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-cybersecurity-professionals`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-operations-professionals`,   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-lawyers`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-accountants`,                lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-project-managers`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-recent-graduates`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-ux-designers`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-consultants`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-supply-chain-professionals`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-medical-professionals`,       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-veterans`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-real-estate-professionals`,  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-entrepreneurs`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },

    // Audience-specific pages
    { url: `${base}/career-coaching-for-job-seekers`,     lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/career-coaching-for-recent-graduates`,lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Competitor comparison pages (high buying intent)
    { url: `${base}/compare`,                            lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/zari-vs-kleo`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-teal`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-jobscan`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-resume-worded`,      lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-linkedin-premium`,   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-chatgpt`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-gemini`,              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-kickresume`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-rezi`,                lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-enhancv`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-novoresume`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-claude`,              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-resumeio`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-perplexity`,          lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-zety`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-microsoft-copilot`,  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-careerflow`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-copy-ai`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-jasper`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-resume-io`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-indeed`,           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-glassdoor`,        lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-wellfound`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-handshake`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },

    // Blog / resources
    { url: `${base}/blog`,                                        lastModified: now, changeFrequency: "weekly",  priority: 0.85 },
    { url: `${base}/blog/best-ai-career-coach`,                   lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-write-resume-with-ai`,            lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-prepare-for-job-interview`,       lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-optimize-linkedin-profile`,       lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/salary-negotiation-tips`,                lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/career-change-guide`,                    lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/promotion-strategy-guide`,               lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/ats-resume-tips`,                        lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/what-is-an-ats`,                         lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/linkedin-headline-examples`,             lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-answer-tell-me-about-yourself`,   lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/resume-summary-examples`,                lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-negotiate-job-offer`,             lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/star-method-interview`,                   lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/behavioral-interview-questions`,          lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-write-a-cover-letter`,            lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/common-interview-questions`,             lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/thank-you-email-after-interview`,        lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/resume-format-guide`,                    lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-ask-for-a-raise`,                 lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/linkedin-summary-examples`,              lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-explain-gaps-in-employment`,      lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/job-search-tips`,                        lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/linkedin-summary-examples`,              lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/weakness-interview-answer`,              lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/interview-questions-to-ask`,             lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-follow-up-on-job-application`,    lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/professional-summary-for-resume`,        lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-cold-email-for-a-job`,           lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/career-goals-examples`,                 lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/linkedin-recommendation-examples`,      lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-write-two-weeks-notice`,         lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/networking-email-templates`,            lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-answer-why-do-you-want-to-work-here`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-evaluate-a-job-offer`,              lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-get-a-job-with-no-experience`,     lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/where-do-you-see-yourself-in-5-years`,    lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/amazon-leadership-principles-interview`,  lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/linkedin-connection-request-message`,     lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-write-a-cover-letter-with-no-experience`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-handle-a-bad-reference`,            lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/remote-job-search-tips`,                   lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/google-interview-prep`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/mckinsey-interview-prep`,                 lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-get-promoted-fast`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/career-change-at-40`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/faang-interview-prep`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/informational-interview-questions`,      lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/highest-paying-jobs`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/signs-you-should-quit-your-job`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/product-manager-interview-questions`,   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/software-engineer-resume`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/data-scientist-resume`,                lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/internal-salary-negotiation`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/career-change-at-50`,                       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/linkedin-optimization-for-recruiters`,     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-google`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-write-a-resume-with-no-experience`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/executive-resume`,                          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/negotiating-equity`,                        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-get-promoted-at-work`,              lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/system-design-interview`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/job-search-while-employed`,                lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/product-manager-resume`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-counter-offer`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/cv-vs-resume`,                            lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/marketing-manager-resume`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-respond-to-job-rejection`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-negotiate-remote-work`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/project-manager-resume`,                 lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-fast`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-ziprecruiter`,                lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-monster`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-dice`,                        lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-linkedin-jobs`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/nurse-resume`,                           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/operations-manager-resume`,              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/personal-brand`,                         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/job-search-burnout`,                     lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/accounting-resume`,                      lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/sales-resume`,                           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/teacher-resume`,                         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/salary-bands`,                           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-simplyhired`,                 lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-careerbuilder`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/hr-resume`,                              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/financial-analyst-resume`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-network`,                         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/imposter-syndrome-at-work`,              lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-google-for-jobs`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-seek`,                        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/graphic-designer-resume`,                lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/cover-letter-examples`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-ask-for-a-promotion`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/entry-level-resume`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-workopolis`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-reed-co-uk`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/finance-resume`,                         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-explain-being-fired`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/salary-expectations-interview`,          lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/data-analyst-resume`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/job-offer-letter`,                       lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/ux-designer-resume`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-job-search-after-layoff`,         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/engineering-manager-resume`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/nursing-interview-questions`,            lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/transferable-skills`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/linkedin-job-search`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-careerone`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-cv-library`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/cybersecurity-resume`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-amazon`,            lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/supply-chain-resume`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-jobstreet`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-totaljobs`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/ux-designer-resume`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },

    // Auth / conversion
    { url: `${base}/signup`,  lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/login`,   lastModified: now, changeFrequency: "monthly", priority: 0.6 },

    // Legal
    { url: `${base}/terms`,   lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
    { url: `${base}/privacy`, lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
    { url: `${base}/security`,lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
  ];

  return staticPages;
}
