import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = process.env.NEXT_PUBLIC_BASE_URL || "https://zaricoach.com";
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    // Core marketing
    { url: base,                                    lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${base}/platform`,                      lastModified: now, changeFrequency: "weekly",  priority: 0.95 },
    { url: `${base}/pricing`,                       lastModified: now, changeFrequency: "weekly",  priority: 0.95 },
    { url: `${base}/use-cases`,                     lastModified: now, changeFrequency: "monthly", priority: 0.9 },

    // Primary keyword landing pages (highest SEO priority)
    { url: `${base}/ai-career-coach`,               lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${base}/ai-resume-writer`,              lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${base}/ai-interview-coach`,            lastModified: now, changeFrequency: "weekly",  priority: 1.0 },
    { url: `${base}/ai-linkedin-optimizer`,         lastModified: now, changeFrequency: "weekly",  priority: 0.95 },

    // Career coach variants
    { url: `${base}/career-coach-tool`,             lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/personal-career-coach`,         lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/free-career-coach`,             lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/career-coaching-software`,      lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Specialty coaching
    { url: `${base}/salary-negotiation-coach`,      lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/promotion-coach`,               lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/career-change-coach`,           lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Service pages
    { url: `${base}/resume-review-service`,         lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/cover-letter-writer`,           lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/linkedin-profile-optimization`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/job-interview-preparation`,     lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Free tool pages (high bottom-of-funnel SEO)
    { url: `${base}/free-resume-checker`,           lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/free-ats-checker`,              lastModified: now, changeFrequency: "monthly", priority: 0.9 },

    // Profession-specific career coaching
    { url: `${base}/career-coach-for-software-engineers`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-product-managers`,   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-executives`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-nurses`,                      lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-teachers`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-marketing-professionals`,     lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-data-scientists`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-finance-professionals`,       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-sales-professionals`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-designers`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-hr-professionals`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-cybersecurity-professionals`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-operations-professionals`,   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-lawyers`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-accountants`,                lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-project-managers`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-recent-graduates`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-ux-designers`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-consultants`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-supply-chain-professionals`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-medical-professionals`,       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-veterans`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-real-estate-professionals`,  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/career-coach-for-entrepreneurs`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },

    // Audience-specific pages
    { url: `${base}/career-coaching-for-job-seekers`,     lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/career-coaching-for-recent-graduates`,lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Competitor comparison pages (high buying intent)
    { url: `${base}/compare`,                            lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/compare/zari-vs-kleo`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-teal`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-jobscan`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-resume-worded`,      lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-linkedin-premium`,   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-chatgpt`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-gemini`,              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-kickresume`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-rezi`,                lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-enhancv`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-novoresume`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-claude`,              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-resumeio`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-perplexity`,          lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-zety`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-microsoft-copilot`,  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-careerflow`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-copy-ai`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-jasper`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-resume-io`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-indeed`,           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-glassdoor`,        lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-wellfound`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-handshake`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },

    // Blog / resources
    { url: `${base}/blog`,                                        lastModified: now, changeFrequency: "weekly",  priority: 0.85 },
    { url: `${base}/blog/best-ai-career-coach`,                   lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-write-resume-with-ai`,            lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-prepare-for-job-interview`,       lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-optimize-linkedin-profile`,       lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/salary-negotiation-tips`,                lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/career-change-guide`,                    lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/promotion-strategy-guide`,               lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/ats-resume-tips`,                        lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/what-is-an-ats`,                         lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/linkedin-headline-examples`,             lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-answer-tell-me-about-yourself`,   lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/resume-summary-examples`,                lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/how-to-negotiate-job-offer`,             lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/blog/star-method-interview`,                   lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/behavioral-interview-questions`,          lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-write-a-cover-letter`,            lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/common-interview-questions`,             lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/thank-you-email-after-interview`,        lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/resume-format-guide`,                    lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-ask-for-a-raise`,                 lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/linkedin-summary-examples`,              lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/how-to-explain-gaps-in-employment`,      lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/job-search-tips`,                        lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/linkedin-summary-examples`,              lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/weakness-interview-answer`,              lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/interview-questions-to-ask`,             lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-follow-up-on-job-application`,    lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/blog/professional-summary-for-resume`,        lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-cold-email-for-a-job`,           lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/career-goals-examples`,                 lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/linkedin-recommendation-examples`,      lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-write-two-weeks-notice`,         lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/networking-email-templates`,            lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-answer-why-do-you-want-to-work-here`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-evaluate-a-job-offer`,              lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-get-a-job-with-no-experience`,     lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/where-do-you-see-yourself-in-5-years`,    lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/amazon-leadership-principles-interview`,  lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/linkedin-connection-request-message`,     lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-write-a-cover-letter-with-no-experience`, lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/how-to-handle-a-bad-reference`,            lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/remote-job-search-tips`,                   lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/google-interview-prep`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/mckinsey-interview-prep`,                 lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-get-promoted-fast`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/career-change-at-40`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/faang-interview-prep`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/informational-interview-questions`,      lastModified: now, changeFrequency: "monthly", priority: 0.87 },
    { url: `${base}/blog/highest-paying-jobs`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/signs-you-should-quit-your-job`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/product-manager-interview-questions`,   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/software-engineer-resume`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/data-scientist-resume`,                lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/internal-salary-negotiation`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/career-change-at-50`,                       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/linkedin-optimization-for-recruiters`,     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-google`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-write-a-resume-with-no-experience`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/executive-resume`,                          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/negotiating-equity`,                        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-get-promoted-at-work`,              lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/system-design-interview`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/job-search-while-employed`,                lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/product-manager-resume`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-counter-offer`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/cv-vs-resume`,                            lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/marketing-manager-resume`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-respond-to-job-rejection`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-negotiate-remote-work`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/project-manager-resume`,                 lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-fast`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-ziprecruiter`,                lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-monster`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-dice`,                        lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-linkedin-jobs`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/nurse-resume`,                           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/operations-manager-resume`,              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/personal-brand`,                         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/job-search-burnout`,                     lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/accounting-resume`,                      lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/sales-resume`,                           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/teacher-resume`,                         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/salary-bands`,                           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-simplyhired`,                 lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-careerbuilder`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/hr-resume`,                              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/financial-analyst-resume`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-network`,                         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/imposter-syndrome-at-work`,              lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-google-for-jobs`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-seek`,                        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/graphic-designer-resume`,                lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/cover-letter-examples`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-ask-for-a-promotion`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/entry-level-resume`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-workopolis`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-reed-co-uk`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/finance-resume`,                         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-explain-being-fired`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/salary-expectations-interview`,          lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/data-analyst-resume`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/job-offer-letter`,                       lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/ux-designer-resume`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-job-search-after-layoff`,         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/engineering-manager-resume`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/nursing-interview-questions`,            lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/transferable-skills`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/linkedin-job-search`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-careerone`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-cv-library`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/cybersecurity-resume`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-amazon`,            lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/supply-chain-resume`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/consulting-resume`,                      lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/legal-resume`,                           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/remote-work-resume`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/salary-negotiation-email`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-naukri`,                      lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-efinancialcareers`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-write-a-linkedin-post`,          lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-microsoft`,         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-prepare-for-an-interview`,       lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-meta`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/healthcare-resume`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/references-on-resume`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/situational-interview-questions`,       lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/what-to-wear-to-an-interview`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-brightermonday`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/marketing-resume`,                      lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-weworkremotely`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-write-a-resignation-letter`,    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/react-developer-resume`,                lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/cloud-engineer-resume`,                 lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-decline-a-job-offer`,            lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/job-acceptance-letter`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/python-developer-resume`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-flexjobs`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-bayt`,                       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/data-engineer-resume`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/internship-resume`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/second-interview-tips`,                 lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-xing`,                       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-gulftalent`,                 lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/mba-resume`,                            lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/devops-resume`,                         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/phone-screen-interview-tips`,           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-stepstone`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-seek-australia`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-jobstreet`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-totaljobs`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/ux-designer-resume`,                     lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-remote-co`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-linkedin-learning`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-himalayas`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-levels-fyi`,                 lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/java-developer-resume`,                 lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/full-stack-developer-resume`,           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-apple`,            lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/machine-learning-engineer-resume`,      lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/linkedin-outreach-message-templates`,   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/product-designer-resume`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-payscale`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-job-hero`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-find-a-mentor`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/executive-presence`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-netflix`,           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-careerly`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-huntr`,                      lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/how-to-get-a-job-at-airbnb`,           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-openai`,           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-stripe`,           lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/ai-engineer-resume`,                    lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/backend-developer-resume`,              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/business-analyst-resume`,               lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/site-reliability-engineer-resume`,      lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/software-engineer-interview-questions`, lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/technical-interview-preparation`,       lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/career-change-at-40`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/career-change-at-50`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/where-do-you-see-yourself-in-5-years`,  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-hired`,                      lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-interview-io`,               lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-lunchclub`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-otta`,                       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/frontend-developer-resume`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/ios-developer-resume`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/scrum-master-resume`,                   lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-uber`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-salesforce`,       lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-deloitte`,         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-at-mckinsey`,         lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/compare/zari-vs-topresume`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-resumelab`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },

    // International landing pages
    { url: `${base}/ai-career-coach-uk`,                        lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/ai-career-coach-canada`,                    lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/ai-career-coach-australia`,                 lastModified: now, changeFrequency: "monthly", priority: 0.95 },

    // Wave 51 — High-volume new content
    { url: `${base}/blog/amazon-behavioral-interview-questions`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/highest-paying-jobs-uk`,               lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/highest-paying-jobs-canada`,           lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/linkedin-profile-tips`,                lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/highest-paying-remote-jobs`,           lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/interview-preparation-checklist`,      lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/data-analyst-interview-questions`,     lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-get-a-job-in-uk`,              lastModified: now, changeFrequency: "monthly", priority: 0.92 },

    // Wave 51 — New compare pages
    { url: `${base}/compare/zari-vs-topinterview`,              lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-ladders`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-talent-com`,                lastModified: now, changeFrequency: "monthly", priority: 0.88 },

    // Wave 52 — Landing pages
    { url: `${base}/online-career-coach`,                       lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-near-me`,                      lastModified: now, changeFrequency: "monthly", priority: 0.95 },

    // Wave 52 — Blog posts
    { url: `${base}/blog/google-behavioral-interview-questions`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/video-interview-tips`,                  lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-into-tech`,                  lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/highest-paying-jobs-no-degree`,         lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/career-change-at-30`,                   lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/panel-interview-questions`,             lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/resume-skills-section`,                 lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/australia-interview-tips`,              lastModified: now, changeFrequency: "monthly", priority: 0.90 },
    { url: `${base}/blog/how-to-get-a-job-in-australia`,         lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-get-a-job-in-canada`,            lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/australia-salary-guide`,                lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/microsoft-behavioral-interview-questions`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-write-a-linkedin-summary`,       lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/negotiating-a-raise`,                   lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/meta-interview-questions`,              lastModified: now, changeFrequency: "monthly", priority: 0.92 },

    // Wave 52 — New compare pages
    { url: `${base}/compare/zari-vs-careercoach-io`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-coachup`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-springboard`,                lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/compare/zari-vs-pathrise`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },

    // Wave 50 — UK/Canada blog content
    { url: `${base}/blog/uk-cv-writing-tips`,                   lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/uk-interview-tips`,                    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/graduate-jobs-uk`,                     lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/cv-template-uk`,                       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/job-search-in-canada`,                 lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/blog/canada-salary-guide`,                  lastModified: now, changeFrequency: "monthly", priority: 0.88 },

    // UK salary pages
    { url: `${base}/salary/software-engineer-salary-london`,          lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-manchester`,      lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-edinburgh`,       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-bristol`,         lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/software-engineer-salary-birmingham`,      lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/product-manager-salary-london`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/product-manager-salary-manchester`,        lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/data-scientist-salary-london`,             lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/data-scientist-salary-manchester`,         lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/machine-learning-engineer-salary-london`,  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/engineering-manager-salary-london`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/frontend-developer-salary-london`,         lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/backend-developer-salary-london`,          lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/devops-engineer-salary-london`,            lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/cybersecurity-engineer-salary-london`,     lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Canada salary pages
    { url: `${base}/salary/software-engineer-salary-toronto`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-vancouver`,       lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-calgary`,         lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/software-engineer-salary-montreal`,        lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/product-manager-salary-toronto`,           lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/product-manager-salary-vancouver`,         lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/data-scientist-salary-toronto`,            lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/data-scientist-salary-montreal`,           lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/machine-learning-engineer-salary-toronto`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/machine-learning-engineer-salary-montreal`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/engineering-manager-salary-toronto`,       lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/ai-engineer-salary-toronto`,               lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Australia salary pages
    { url: `${base}/salary/software-engineer-salary-sydney`,          lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/software-engineer-salary-melbourne`,       lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/product-manager-salary-sydney`,            lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/data-scientist-salary-sydney`,             lastModified: now, changeFrequency: "monthly", priority: 0.85 },

    // Salary guides index + calculator + research report
    { url: `${base}/salary`,                                    lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/salary-calculator`,                         lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/job-search-statistics-2025`,           lastModified: now, changeFrequency: "monthly", priority: 0.92 },

    // Salary pages — top 40 highest-traffic combinations
    { url: `${base}/salary/software-engineer-salary-san-francisco`,  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-new-york-city`,  lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-seattle`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-austin`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-remote`,         lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/software-engineer-salary-boston`,         lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/software-engineer-salary-los-angeles`,    lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/software-engineer-salary-chicago`,        lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/product-manager-salary-san-francisco`,    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/product-manager-salary-new-york-city`,    lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/product-manager-salary-seattle`,          lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/product-manager-salary-remote`,           lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/data-scientist-salary-san-francisco`,     lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/data-scientist-salary-new-york-city`,     lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/data-scientist-salary-seattle`,           lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/machine-learning-engineer-salary-san-francisco`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/machine-learning-engineer-salary-new-york-city`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/ai-engineer-salary-san-francisco`,        lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/engineering-manager-salary-san-francisco`, lastModified: now, changeFrequency: "monthly", priority: 0.88 },
    { url: `${base}/salary/engineering-manager-salary-new-york-city`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/frontend-developer-salary-san-francisco`,  lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/frontend-developer-salary-austin`,         lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/backend-developer-salary-san-francisco`,   lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/devops-engineer-salary-san-francisco`,     lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/devops-engineer-salary-seattle`,           lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/site-reliability-engineer-salary-san-francisco`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/cloud-engineer-salary-san-francisco`,      lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/data-engineer-salary-san-francisco`,       lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/ios-developer-salary-san-francisco`,       lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/cybersecurity-engineer-salary-washington-dc`, lastModified: now, changeFrequency: "monthly", priority: 0.85 },
    { url: `${base}/salary/software-engineer-salary-toronto`,         lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/salary/software-engineer-salary-london`,          lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/salary/product-manager-salary-london`,            lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/salary/data-scientist-salary-london`,             lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/salary/software-engineer-salary-washington-dc`,   lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/salary/product-designer-salary-san-francisco`,    lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/salary/technical-program-manager-salary-san-francisco`, lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/salary/business-analyst-salary-new-york-city`,    lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/salary/scrum-master-salary-san-francisco`,        lastModified: now, changeFrequency: "monthly", priority: 0.82 },
    { url: `${base}/salary/data-analyst-salary-new-york-city`,        lastModified: now, changeFrequency: "monthly", priority: 0.82 },

    // Wave 53 — Landing pages
    { url: `${base}/cover-letter-generator`,   lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/linkedin-profile-writer`,  lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/resume-checker`,           lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/ai-career-coach-india`,    lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/ai-career-coach-singapore`,lastModified: now, changeFrequency: "monthly", priority: 0.95 },

    // Wave 53 — Blog posts
    { url: `${base}/blog/highest-paying-jobs-australia`,    lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/career-development-plan`,          lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/management-interview-questions`,   lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-get-a-job-in-dubai`,        lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/chronological-vs-functional-resume`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/best-tech-companies-to-work-for`,  lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-use-linkedin-to-find-a-job`,lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-get-a-job-abroad`,          lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-write-a-personal-statement`,lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/work-from-home-jobs`,              lastModified: now, changeFrequency: "monthly", priority: 0.92 },

    // Wave 54 — City career coach pages
    { url: `${base}/career-coach-new-york`,       lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-los-angeles`,    lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-chicago`,        lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-san-francisco`,  lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-seattle`,        lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-boston`,         lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-austin`,         lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-houston`,        lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-atlanta`,        lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-denver`,         lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-miami`,          lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-washington-dc`,  lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-dallas`,         lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-coach-philadelphia`,   lastModified: now, changeFrequency: "monthly", priority: 0.95 },

    // Wave 54 — Service pages
    { url: `${base}/best-resume-writing-service`,  lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/mock-interview-online`,         lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/professional-resume-writer`,    lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/executive-resume-writer`,       lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/resume-optimizer`,              lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/career-counseling-online`,      lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/interview-coaching-service`,    lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/job-search-coaching`,           lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/executive-career-coaching`,     lastModified: now, changeFrequency: "monthly", priority: 0.95 },

    // Wave 54 — International pages
    { url: `${base}/ai-career-coach-germany`,       lastModified: now, changeFrequency: "monthly", priority: 0.95 },
    { url: `${base}/ai-career-coach-dubai`,         lastModified: now, changeFrequency: "monthly", priority: 0.95 },

    // Wave 54 — Blog posts
    { url: `${base}/blog/what-is-a-good-ats-score`,             lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-long-should-a-resume-be`,          lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/should-i-use-chatgpt-to-write-my-resume`, lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/is-linkedin-premium-worth-it`,         lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/tech-layoff-survival-guide`,           lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/first-90-days-new-job`,                lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-get-into-product-management`,   lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-become-a-software-engineer`,    lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-many-jobs-to-apply-per-day`,       lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-long-does-it-take-to-find-a-job`,  lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/what-to-put-on-a-resume`,              lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/how-to-get-a-job-in-germany`,          lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/highest-paying-jobs-singapore`,        lastModified: now, changeFrequency: "monthly", priority: 0.92 },
    { url: `${base}/blog/highest-paying-jobs-dubai`,            lastModified: now, changeFrequency: "monthly", priority: 0.92 },

    // Auth / conversion
    { url: `${base}/signup`,  lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/login`,   lastModified: now, changeFrequency: "monthly", priority: 0.6 },

    // Legal
    { url: `${base}/terms`,   lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
    { url: `${base}/privacy`, lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
    { url: `${base}/security`,lastModified: now, changeFrequency: "yearly",  priority: 0.3 },
  ];

  return staticPages;
}
