import Link from "next/link";
import { ZariLogo } from "@/components/zari-logo";

export const metadata = { title: "Terms of Service – Zari" };

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "#F8F9FC", fontFamily: "Inter, system-ui, sans-serif" }}>
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "40px 24px 80px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 40 }}>
          <Link href="/" style={{ display: "flex", alignItems: "center", gap: 8, textDecoration: "none" }}>
            <ZariLogo size={28} />
            <span style={{ fontSize: 16, fontWeight: 800, background: "linear-gradient(135deg, #4F46E5, #7C3AED)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>Zari</span>
          </Link>
        </div>

        <h1 style={{ fontSize: 28, fontWeight: 800, color: "#0F172A", marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 14, color: "#64748B", marginBottom: 40 }}>Last updated: May 6, 2025</p>

        {[
          {
            title: "1. Acceptance of Terms",
            body: "By accessing or using Zari (\"the Service\"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.",
          },
          {
            title: "2. Description of Service",
            body: "Zari is an AI-powered career coaching platform that assists users with job searching, resume building, interview preparation, and related career activities. The Service is provided by Askia Technologies Inc.",
          },
          {
            title: "3. Account Registration",
            body: "You must provide accurate, complete information when creating an account. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. You must be at least 18 years old to use the Service.",
          },
          {
            title: "4. Acceptable Use",
            body: "You agree not to misuse the Service. Prohibited activities include: attempting to reverse engineer or scrape the Service, using the Service to generate spam or misleading content, circumventing any access controls, or reselling access to the Service without authorization.",
          },
          {
            title: "5. Subscription and Billing",
            body: "Paid plans are billed in advance on a monthly or annual basis. You may cancel at any time; your subscription will remain active until the end of the current billing period. Refunds are handled on a case-by-case basis at our discretion.",
          },
          {
            title: "6. AI-Generated Content",
            body: "Content generated by Zari's AI tools is provided for informational and assistive purposes. You are responsible for reviewing and verifying any content before using it professionally. Zari does not guarantee job placement or specific career outcomes.",
          },
          {
            title: "7. Intellectual Property",
            body: "Zari retains ownership of the platform, its underlying technology, and system prompts. Content you input remains yours. Content generated on your behalf is licensed to you for personal, professional use.",
          },
          {
            title: "8. Privacy",
            body: "Your use of the Service is governed by our Privacy Policy, which is incorporated into these Terms by reference.",
          },
          {
            title: "9. Limitation of Liability",
            body: "To the maximum extent permitted by law, Askia Technologies Inc. shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.",
          },
          {
            title: "10. Changes to Terms",
            body: "We may update these Terms from time to time. We will notify you of material changes via email or in-product notice. Continued use of the Service after changes constitutes acceptance.",
          },
          {
            title: "11. Contact",
            body: "For questions about these Terms, contact us at legal@askiatech.com.",
          },
        ].map(({ title, body }) => (
          <div key={title} style={{ marginBottom: 32 }}>
            <h2 style={{ fontSize: 16, fontWeight: 700, color: "#1E293B", marginBottom: 8 }}>{title}</h2>
            <p style={{ fontSize: 14, color: "#475569", lineHeight: 1.7, margin: 0 }}>{body}</p>
          </div>
        ))}

        <div style={{ borderTop: "1px solid #E2E8F0", paddingTop: 24, marginTop: 16 }}>
          <Link href="/privacy" style={{ fontSize: 14, color: "#4F46E5", marginRight: 24 }}>Privacy Policy</Link>
          <Link href="/" style={{ fontSize: 14, color: "#64748B" }}>Back to Zari</Link>
        </div>
      </div>
    </div>
  );
}
