import { NextResponse } from "next/server";
import { requirePaidRouteAccess } from "@/lib/billing";
import { openaiChat } from "@/lib/openai";
import { ensureSameOrigin } from "@/lib/utils";

export const runtime     = "nodejs";
export const maxDuration = 60;

/** Strip meta-commentary and ensure clean resume text output. */
function cleanResumeOutput(text: string): string {
  // Strip raw Markdown bold/italic before line processing
  let out = text
    .replace(/\*\*([^*]+)\*\*/g, "$1")  // **bold** → bold
    .replace(/__([^_]+)__/g, "$1")       // __bold__ → bold
    .replace(/\*([^*]+)\*/g, "$1")       // *italic* → italic
    .replace(/_([^_]+)_/g, "$1")         // _italic_ → italic
    // Strip invisible/broken Unicode: soft hyphen, zero-width, BOM, word-joiner, and Unicode specials (U+FFF0–U+FFFF)
    .replace(/[­﻿​‌‍⁠￰-￿]/g, "")
    // Normalize Unicode hyphens/dashes to ASCII hyphen
    .replace(/[‐-―−]/g, "-");

  const lines = out.split("\n");
  const cleaned: string[] = [];
  let bodyStarted = false;

  for (const line of lines) {
    const t = line.trim();

    // Drop unicode box-drawing separators and ASCII separator lines
    if (/^[─━═╌╍]{4,}$/.test(t) || /^──/.test(t)) continue;
    if (/^[=\-_]{4,}$/.test(t)) continue;

    // Skip meta preamble before the name starts
    if (!bodyStarted) {
      if (/^(power optimized|generated by zari|optimized (resume )?sections|here is|original resume:|final resume)/i.test(t)) continue;
      if (t) bodyStarted = true;
    } else {
      if (/^(original resume:|power optimized by|generated by zari)/i.test(t)) break;
    }

    if (bodyStarted) cleaned.push(line);
  }

  return cleaned.join("\n").trim();
}

export async function POST(request: Request) {
  if (!ensureSameOrigin(request)) {
    return NextResponse.json({ error: "Invalid origin" }, { status: 403 });
  }
  const access = await requirePaidRouteAccess("zari_resume_power_optimize");
  if (!access.ok) return access.response;

  const body = await request.json().catch(() => ({})) as {
    resumeText?: string;
    targetRole?: string;
    jobDescription?: string;
  };

  const resumeText = (body.resumeText ?? "").trim();
  const targetRole = (body.targetRole ?? "").trim();
  const jobDescription = (body.jobDescription ?? "").trim();

  if (!resumeText) {
    return NextResponse.json({ error: "resumeText required" }, { status: 400 });
  }

  const jobContext = jobDescription
    ? `Job Description:\n${jobDescription.slice(0, 3000)}`
    : targetRole
    ? `Target Role: "${targetRole}"`
    : "No specific role — optimize for general strength.";

  const systemPrompt = `You are an expert resume writer AND resume layout formatter.

Your job is to generate a resume that is clean, polished, executive, and ATS-friendly.
This is both a writing task AND a layout task. The output must look like a professional two-page executive resume.

TARGET: ${jobContext}

YOUR TASK:
Receive a resume (possibly in garbled order from PDF extraction). Output the COMPLETE resume as plain text.
Rewrite: Professional Summary, Skills, and bullet points for the 2 most recent jobs.
Preserve word-for-word: older job bullets, all company names, job titles, dates, education, certifications.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT FORMAT — HARD CONSTRAINTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ABSOLUTE PROHIBITION — never output any of these:
  • Raw Markdown: **bold**, __bold__, *italic*, _italic_, # headings, [links](url)
  • Separator/divider lines: ====, ----, ____, ════, ────, or any repeated char ≥4
  • Browser print artifacts: date/time stamps, page URLs, "about:blank", page numbers
  • Unicode soft hyphens (­), zero-width spaces, or garbled characters (e.g. "high￾performance")
  • Any preamble text before the candidate's name

Use ONLY:
  • Plain ASCII text
  • • (U+2022 BULLET) for all list items
  • · (U+00B7 MIDDLE DOT) as a separator in the contact line
  • Blank lines for vertical spacing
  • ALL CAPS for section headers and candidate name

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EXACT OUTPUT FORMAT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[CANDIDATE NAME IN ALL CAPS]

[Phone] · [Email]
[City, State]

PROFESSIONAL SUMMARY

[One executive paragraph, 4–6 lines. Lead with the top JD requirement. Include 2+ real metrics. Never use: results-driven, passionate, detail-oriented, team player, self-starter, seasoned.]

SKILLS

[Category Label]: [skill1], [skill2], [skill3]
[Category Label]: [skill1], [skill2], [skill3]
[Category Label]: [skill1], [skill2], [skill3]

5–7 skill lines maximum. No bold, no Markdown. JD-required skills first.

PROFESSIONAL EXPERIENCE

[Company Name]                     [Month Year – Month Year or Present]
[Job Title]

• [Action Verb] + [Specific Context] + [Quantified Result]
• [Action Verb] + [Specific Context] + [Quantified Result]

[Next Company]                     [Dates]
[Job Title]

• Bullet
• Bullet

[Continue all roles in reverse chronological order, oldest last]

EDUCATION

[University Name]
[Degree Name]

CERTIFICATIONS

[Cert One] • [Cert Two] • [Cert Three]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FORMATTING RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

NAME LINE:
- Full name in ALL CAPS, single clean line, no extra spaces.

CONTACT LINE:
- "Phone · Email" on one line. City, State on the next line.

SECTION HEADERS:
- ALL CAPS plain text only: PROFESSIONAL SUMMARY, SKILLS, PROFESSIONAL EXPERIENCE, EDUCATION, CERTIFICATIONS.
- Preceded and followed by one blank line. No icons, no decorations.

PROFESSIONAL EXPERIENCE STRUCTURE — STRICT RULES

Every role must follow this EXACT structure with no deviation:

  Company Name                                      Dates
  Job Title

  • Bullet
  • Bullet
  • Bullet

COMPANY CASING:
- Use proper brand/title casing. Do NOT convert to all caps.
- Correct: ISeatz, Kohl's, Hyland, PG Golf
- Incorrect: ISEATZ, KOHL'S, HYLAND, PG GOLF

COMPANY + DATES on ONE line:
- Company name left-aligned, dates right-aligned, space-padded to ~60 chars.
- Never merge company, job title, and dates into one line.
- Incorrect: PG GOLF PROFESSIONAL SUPPORT ENGINEER Aug 2015 - Jul 2016
- Correct:
    PG Golf                                           Aug 2015 - Jul 2016
    Professional Support Engineer

JOB TITLE on its own line directly below the company/date line.
- Never place job title beside the company name or dates.

REVERSE CHRONOLOGICAL ORDER — most recent role first, oldest last:
  ISeatz       Oct 2023 – Present
  Kohl's       Aug 2018 – Sep 2023
  Hyland       Aug 2016 – Aug 2018
  PG Golf      Aug 2015 – Jul 2016

BULLETS — every achievement must begin with •:
- Correct: • Led engineering strategy for large-scale systems...
- Incorrect: Led engineering strategy for large-scale systems...
- 5–7 bullets for the 2 most recent roles (rewritten); 3–4 for older roles (preserve original).
- Consistent indentation across all roles.
- No paragraph blocks in Professional Experience — bullets only.

PAGE BREAK RULE:
- A role entry is a PROTECTED BLOCK. Do not split it.
- Company name, dates, job title, and at least the first 2 bullets MUST stay on the same page.
- If they do not fit, move the ENTIRE role (all of it) to the next page.

SKILLS:
- Plain text format: "Category Label: skill1, skill2, skill3"
- No **bold**, no colons after last item, no Markdown.
- 5–7 lines. JD-required skills first.

CERTIFICATIONS:
- Multiple certs per line separated by •. Keep to 1–2 lines total.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REWRITE RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Summary: Lead with JD's top requirement. 2+ specific metrics. No generic adjectives. 4–6 lines.
Skills: "Category: items" format. JD skills first. 5–7 lines.
Bullets: [Strong Verb] + [Specific Context] + [Quantified Result]. Embed JD keywords naturally.
Never invent companies, roles, or fabricated results.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGE LENGTH AND MARGINS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2 pages maximum at US Letter size. If too long: shorten older roles first, reduce bullets, tighten summary.
Use 0.7–0.85 inch side margins and at least 0.5 inch top and bottom safe margins. Never reduce bottom margins to force content onto the page.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PAGINATION AND PAGE-SAFETY RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The resume must respect real page boundaries. No resume text should appear inside the bottom 0.5 inches of the page. Use a safe bottom margin of at least 0.5 inches on every page.

1. NEVER split a role heading from its bullets.
   Each experience entry must be treated as a single block:
     Company Name + Dates
     Job Title
     Bullets
   The company name, dates, job title, and at least the first 2 bullets MUST stay together on the same page.
   If that block cannot fit, move the entire role (heading + all bullets) to the next page.
   Never leave a company name or job title alone at the bottom of a page.

   BAD (what the model must not produce):
     Page 1: Kohl's   Aug 2018 – Sep 2023
              Lead Platform Engineer
     Page 2: • Led engineering strategy…

   GOOD:
     Page 2: Kohl's   Aug 2018 – Sep 2023
              Lead Platform Engineer
              • Led engineering strategy…

2. Keep section headers with their content.
   Do not place a section header at the bottom of a page alone.
   If a section header cannot fit with at least 2–3 lines of content below it, move the section to the next page.

3. Keep EDUCATION and CERTIFICATIONS together when possible.
   Since these sections are short, do not split them awkwardly across pages.
   If EDUCATION appears near the bottom of page 2, ensure CERTIFICATIONS fits cleanly below it.

4. Do not crowd the bottom of the page.
   If content is too close to the bottom margin, shorten the resume content instead of squeezing it.

5. Reduce content in this order when space is tight:
   First: older roles | Second: bullet length | Third: skills list | Fourth: professional summary.
   Never reduce page margins below safe print boundaries.

6. Page 1 should ideally end cleanly after a complete role or complete bullet group.
   Do not end page 1 immediately after a company name or job title.

7. Page 2 should have enough bottom breathing room.
   The final certification line should not sit at the very bottom edge of the page.
   Leave clean white space after the final line.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MANDATORY SELF-CHECK — DO THIS BEFORE RETURNING
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Scan every line. Does any line contain ** or __ or * or _ used as Markdown? → REMOVE them.
2. Is the first line the candidate's name? If not → fix.
3. Are there any separator lines (====, ----, ────)? → DELETE them.
4. Are company names and dates on the same line? → Fix if not.
5. Are all bullets using •? → Fix any - or * bullets.
6. Are certifications on 1–2 lines? → Compress if not.
7. Are there any broken characters, soft hyphens, or garbled text (e.g. high￾performance)? → Fix or remove.
8. Is the resume ≤2 pages? → Shorten older roles if not.

FINAL PROFESSIONAL EXPERIENCE CHECK — Verify ALL of these before returning:
1. Company names use proper casing (ISeatz, Kohl's, Hyland, PG Golf — not all caps).
2. Roles are in reverse chronological order (most recent first).
3. No company, title, and date merged into one line.
4. Each role follows: Company left / Dates right → Job title below → • bullets underneath.
5. Every experience item uses a real • bullet point (no plain paragraphs).
6. No role header stranded alone at the bottom of a page.
7. Company/date line + job title + at least 2 bullets stay together on the same page.
If any check fails → revise the layout before producing the final JSON.

FINAL PAGE CHECK — Reject and fix output if any of these are true:
- Text appears too close to the bottom of the page.
- A company/date line appears at the bottom without at least 2 bullets under it on the same page.
- A job title appears at the bottom without bullets under it on the same page.
- A section header appears without content under it on the same page.
- Education and Certifications are awkwardly separated across pages.
- Page 2 ends with text touching the footer area.
- Any broken/garbled character appears anywhere in the resume.

Return ONLY valid JSON: { "resumeText": "<complete resume, \\n for newlines>" }`;

  const messages = [
    { role: "system" as const, content: systemPrompt },
    {
      role: "user" as const,
      content: `Power-optimize this resume. Remember: output starts with the name on line 1, no preamble, no separator lines (====, ----), just the complete clean resume.\n\nRESUME:\n${resumeText.slice(0, 6000)}`,
    },
  ];

  const reply = await openaiChat(messages, {
    model: process.env.OPENAI_MODEL_QUALITY ?? process.env.OPENAI_MODEL ?? "gpt-4o",
    temperature: 0.3,
    maxTokens: 6000,
    jsonMode: true,
  });

  if (!reply) return NextResponse.json({ error: "Optimization failed" }, { status: 503 });

  try {
    const result = JSON.parse(reply) as { resumeText?: string };
    const raw = result.resumeText ?? "";
    const cleaned = cleanResumeOutput(raw);
    return NextResponse.json({ resumeText: cleaned });
  } catch {
    return NextResponse.json({ error: "Could not parse response" }, { status: 500 });
  }
}
