import { NextResponse } from "next/server";
import { requirePaidRouteAccess } from "@/lib/billing";
import { openaiChat } from "@/lib/openai";
import { ensureSameOrigin } from "@/lib/utils";

export const runtime     = "nodejs";
export const maxDuration = 60;

/** Strip any meta-commentary the model might have snuck in.
 *  Preserves intentional = and - separator lines (part of the template).
 *  Drops unicode box-drawing chars and AI preamble/postamble. */
function cleanResumeOutput(text: string): string {
  const lines = text.split("\n");
  const cleaned: string[] = [];
  let bodyStarted = false;

  for (const line of lines) {
    const t = line.trim();

    // Drop unicode box-drawing separators anywhere — only ASCII = and - are valid
    if (/^[─━═╌╍]{4,}$/.test(t) || /^──/.test(t)) continue;

    // Skip meta preamble before the name starts
    if (!bodyStarted) {
      if (/^(power optimized|generated by zari|optimized (resume )?sections|here is|original resume:)/i.test(t)) continue;
      if (t) bodyStarted = true;
    } else {
      // Stop at trailing meta sections
      if (/^(original resume:|power optimized by|generated by zari)/i.test(t)) break;
    }

    if (bodyStarted) cleaned.push(line);
  }

  return cleaned.join("\n").trim();
}

export async function POST(request: Request) {
  if (!ensureSameOrigin(request)) {
    return NextResponse.json({ error: "Invalid origin" }, { status: 403 });
  }
  const access = await requirePaidRouteAccess("zari_resume_power_optimize");
  if (!access.ok) return access.response;

  const body = await request.json().catch(() => ({})) as {
    resumeText?: string;
    targetRole?: string;
    jobDescription?: string;
  };

  const resumeText = (body.resumeText ?? "").trim();
  const targetRole = (body.targetRole ?? "").trim();
  const jobDescription = (body.jobDescription ?? "").trim();

  if (!resumeText) {
    return NextResponse.json({ error: "resumeText required" }, { status: 400 });
  }

  const jobContext = jobDescription
    ? `Job Description:\n${jobDescription.slice(0, 3000)}`
    : targetRole
    ? `Target Role: "${targetRole}"`
    : "No specific role — optimize for general strength.";

  const systemPrompt = `You are an expert resume formatter and resume writer performing a targeted Power Optimization.

TARGET: ${jobContext}

YOUR TASK:
Receive a resume (possibly in garbled order from PDF extraction). Output the COMPLETE resume as plain text using the EXACT template and format below. Rewrite: Professional Summary, Skills, and bullet points for the 2 most recent jobs. Preserve word-for-word: older job bullets, all company names, job titles, dates, education, certifications.

════════════════════════════════════════════════════════════
REQUIRED TEMPLATE — replicate this EXACT structure:
════════════════════════════════════════════════════════════

FIRST LAST

(555) 555-5555 · email@email.com
City, State

============================================================

                        PROFESSIONAL SUMMARY

[One executive paragraph, left-aligned, 5–7 lines. Lead with the JD's top requirement. Include 2+ real metrics from their experience. No "results-driven", "passionate", "detail-oriented", "team player", "self-starter", "seasoned".]

------------------------------------------------------------

                             SKILLS

• Category: skill1, skill2, skill3
• Category: skill1, skill2, skill3
• Category: skill1, skill2, skill3
• Category: skill1, skill2, skill3
• Category: skill1, skill2, skill3

------------------------------------------------------------

                      PROFESSIONAL EXPERIENCE

Company Name                                      Jan 20XX – Present
Job Title

• Bullet: Action Verb + Specific Context + Quantified Result
• Bullet
• Bullet

Company Name                                      Jan 20XX – Jan 20XX
Job Title

• Bullet
• Bullet
• Bullet

[Continue for ALL jobs — older jobs copy bullets EXACTLY, no changes]

------------------------------------------------------------

                           EDUCATION

University Name
Degree Name

------------------------------------------------------------

                         CERTIFICATIONS

• Certification One              • Certification Two
• Certification Three            • Certification Four

════════════════════════════════════════════════════════════
FORMATTING RULES — follow exactly:
════════════════════════════════════════════════════════════

NAME LINE:
- Full name in ALL CAPS on its own line.
- Name is centered using spaces if possible; if not, just output it on its own line.

CONTACT LINE:
- Phone · Email on one line, centered.
- City, State on the next line, centered.

SEPARATORS:
- After contact info: one thick separator line of 60 "=" characters.
- Between PROFESSIONAL SUMMARY and SKILLS: one thin separator of 60 "-" characters.
- Between SKILLS and PROFESSIONAL EXPERIENCE: one thin separator of 60 "-" characters.
- Before EDUCATION: one thin separator of 60 "-" characters.
- Before CERTIFICATIONS: one thin separator of 60 "-" characters.

SECTION HEADERS:
- ALL CAPS, bold if supported — use plain text: PROFESSIONAL SUMMARY, SKILLS, PROFESSIONAL EXPERIENCE, EDUCATION, CERTIFICATIONS.
- Indent headers with spaces to visually center them (approx 20–24 spaces before the heading for narrow headers, fewer for longer ones).
- Each section header on its own line, preceded and followed by a blank line.

EXPERIENCE ENTRIES:
- Company name left-aligned, dates right-aligned on the same line (use spaces to push dates to ~58+ chars).
- Job title on the next line, bold/plain left-aligned.
- One blank line before bullets.
- Use • for every bullet.
- 5–8 bullets for the 2 most recent roles (rewritten); 3–5 bullets for older roles (copy exactly).
- One blank line between roles.

SKILLS:
- Each line starts with •
- Format: • Category Label: skill1, skill2, skill3
- 5–7 skill lines.
- Reorder so JD-required skills appear first.

EDUCATION:
- School name on one line.
- Degree below it.

CERTIFICATIONS:
- Use • bullets.
- Attempt 2–3 per line (tab-separated or spaced) for a column effect.

════════════════════════════════════════════════════════════
REWRITE RULES:
════════════════════════════════════════════════════════════
Summary: Lead with the JD's top requirement. 2+ specific metrics. No generic adjectives. 5–7 lines.
Skills: "Category: items" format. JD skills first. 5–7 lines.
Bullets: [Strong Verb] + [Specific Context] + [Quantified Result]. Embed JD keywords naturally. Keep all real achievements. Never invent companies, roles, or fabricated results.

════════════════════════════════════════════════════════════
CRITICAL RULES:
════════════════════════════════════════════════════════════
- Output starts with the person's name on LINE 1. Nothing before it.
- NO preamble: do not write "Here is", "Optimized resume:", "OPTIMIZED SECTIONS", or any intro.
- NO meta-commentary anywhere in the output.
- NO "Original resume:" section at the end.
- Use • for all bullet points (never -, *, or numbers).
- Reconstruct correct section order even if input is garbled.
- Sections must appear in this exact order: name → contact → separator → PROFESSIONAL SUMMARY → separator → SKILLS → separator → PROFESSIONAL EXPERIENCE → separator → EDUCATION → separator → CERTIFICATIONS.

Return ONLY valid JSON: { "resumeText": "<complete resume, \\n for newlines>" }`;

  const messages = [
    { role: "system" as const, content: systemPrompt },
    {
      role: "user" as const,
      content: `Power-optimize this resume. Remember: output starts with the name on line 1, no preamble, no meta-text, just the complete resume.\n\nRESUME:\n${resumeText.slice(0, 6000)}`,
    },
  ];

  const reply = await openaiChat(messages, {
    model: process.env.OPENAI_MODEL_QUALITY ?? process.env.OPENAI_MODEL ?? "gpt-4o",
    temperature: 0.3,
    maxTokens: 6000,
    jsonMode: true,
  });

  if (!reply) return NextResponse.json({ error: "Optimization failed" }, { status: 503 });

  try {
    const result = JSON.parse(reply) as { resumeText?: string };
    const raw = result.resumeText ?? "";
    const cleaned = cleanResumeOutput(raw);
    return NextResponse.json({ resumeText: cleaned });
  } catch {
    return NextResponse.json({ error: "Could not parse response" }, { status: 500 });
  }
}
