import { NextResponse } from "next/server";
import { openaiChat } from "@/lib/openai";
import { ensureSameOrigin } from "@/lib/utils";

/** Strip any meta-commentary the model might have snuck in */
function cleanResumeOutput(text: string): string {
  const lines = text.split("\n");
  const cleaned: string[] = [];
  let bodyStarted = false;

  for (const line of lines) {
    const t = line.trim();

    // Skip obvious meta lines before the name starts
    if (!bodyStarted) {
      if (
        /^(power optimized|generated by zari|optimized (resume )?sections|here is|original resume:)/i.test(t) ||
        /^[─═\-]{4,}$/.test(t) ||
        /^──/.test(t)
      ) continue;
      // First non-empty, non-meta line = the name → body has started
      if (t) bodyStarted = true;
    } else {
      // Inside body: still drop stray separator/meta lines
      if (/^[─═]{4,}$/.test(t)) continue;
      if (/^(original resume:|power optimized by|generated by zari)/i.test(t)) break; // stop here
    }

    if (bodyStarted) cleaned.push(line);
  }

  return cleaned.join("\n").trim();
}

export async function POST(request: Request) {
  if (!ensureSameOrigin(request)) {
    return NextResponse.json({ error: "Invalid origin" }, { status: 403 });
  }

  const body = await request.json().catch(() => ({})) as {
    resumeText?: string;
    targetRole?: string;
    jobDescription?: string;
  };

  const resumeText = (body.resumeText ?? "").trim();
  const targetRole = (body.targetRole ?? "").trim();
  const jobDescription = (body.jobDescription ?? "").trim();

  if (!resumeText) {
    return NextResponse.json({ error: "resumeText required" }, { status: 400 });
  }

  const jobContext = jobDescription
    ? `Job Description:\n${jobDescription.slice(0, 3000)}`
    : targetRole
    ? `Target Role: "${targetRole}"`
    : "No specific role — optimize for general strength.";

  const systemPrompt = `You are a resume writer performing a targeted Power Optimization.

TARGET: ${jobContext}

YOUR TASK:
Receive a resume (possibly in garbled order from PDF extraction). Output the COMPLETE resume as plain text, with ONLY these 3 sections rewritten: Professional Summary, Skills, and the bullet points for the 2 most recent jobs. All other content (older job bullets, company names, job titles, dates, education, certifications) must be preserved word-for-word.

═══════════════════════════════════════════
REQUIRED OUTPUT FORMAT — follow exactly:
═══════════════════════════════════════════

[PERSON'S FULL NAME IN ALL CAPS]
[phone · email]
[City, State]

PROFESSIONAL SUMMARY
[Rewritten summary: 3-5 sentences. Lead with the exact job title from the JD. Include 2+ real metrics from their experience. Sound like a real senior professional. No "results-driven", "passionate", "detail-oriented", "team player".]

SKILLS
[Rewritten skills in "Category: skill1, skill2, skill3" format. Put JD-required skills first. One line per category.]

PROFESSIONAL EXPERIENCE
[MOST RECENT JOB COMPANY NAME]
[Job Title]
[Start Date] - [End Date]
• [Rewritten bullet: Action Verb + What + Measurable Result]
• [Rewritten bullet]
[continue for all bullets of this job]

[SECOND MOST RECENT JOB COMPANY NAME]
[Job Title]
[Start Date] - [End Date]
• [Rewritten bullet]
• [Rewritten bullet]
[continue for all bullets of this job]

[ALL OLDER JOBS — copy their bullets EXACTLY as given, same company/title/dates/bullets, no changes]

EDUCATION
[Copy exactly as given]

CERTIFICATIONS
• [Copy exactly as given]
[continue for all certifications]

═══════════════════════════════════════════
REWRITE RULES:
═══════════════════════════════════════════
Summary: Lead with the JD's top requirement. 2+ specific metrics. No generic adjectives.
Skills: Keep "Category: items" format. JD skills first. Remove pure soft skills.
Bullets: [Strong Verb] + [Specific Context] + [Quantified Result]. Embed JD keywords naturally. Keep all real achievements. Never invent companies, roles, or wholly fabricated results.

═══════════════════════════════════════════
CRITICAL RULES:
═══════════════════════════════════════════
- Output starts with the person's name on LINE 1. Nothing before it.
- NO preamble: do not write "Here is", "Optimized resume:", "OPTIMIZED SECTIONS", or any intro.
- NO meta-commentary anywhere in the output.
- NO "Original resume:" section at the end.
- NO separator lines of dashes or equals signs.
- Section headers are ALL CAPS, plain text (e.g. PROFESSIONAL SUMMARY — no decoration).
- Use • for all bullet points.
- Reconstruct correct section order even if input is garbled.

Return ONLY valid JSON: { "resumeText": "<complete resume, \\n for newlines>" }`;

  const messages = [
    { role: "system" as const, content: systemPrompt },
    {
      role: "user" as const,
      content: `Power-optimize this resume. Remember: output starts with the name on line 1, no preamble, no meta-text, just the complete resume.\n\nRESUME:\n${resumeText.slice(0, 6000)}`,
    },
  ];

  const reply = await openaiChat(messages, {
    model: process.env.OPENAI_MODEL_QUALITY ?? process.env.OPENAI_MODEL ?? "gpt-4o",
    temperature: 0.3,
    maxTokens: 6000,
    jsonMode: true,
  });

  if (!reply) return NextResponse.json({ error: "Optimization failed" }, { status: 503 });

  try {
    const result = JSON.parse(reply) as { resumeText?: string };
    const raw = result.resumeText ?? "";
    const cleaned = cleanResumeOutput(raw);
    return NextResponse.json({ resumeText: cleaned });
  } catch {
    return NextResponse.json({ error: "Could not parse response" }, { status: 500 });
  }
}
